/* rip
{id:"ABC/Palm Springs",cat:"News",des:"ABC KESQ California Palm Springs The Desert's News Leader.",uri:"https://kesq.com/feed",ext:"https://kesq.com"},
{id:"NBC/Palm Springs",cat:"News",des:"NBC KMIR California Palm Springs News, Weather, Traffic, Breaking News where Breaking News comes first.",uri:"https://nbcpalmsprings.com/feed",ext:"https://nbcpalmsprings.com"},
{id:"CBS/Palm Springs",cat:"News",des:"CBS KESQ California Palm Springs Daily News Headlines Morning Forecast Breaking News Severe Weather.",uri:"https://kesq.com/feed",ext:"https://kesq.com"},
{id:"ABC",cat:"News",des:"ABC KSBW California Salinas Action News 8 is your source for the Latest Local Headlines.",uri:"https://www.ksbw.com/topstories-rss",ext:"https://www.ksbw.com"},
{id:"Central News",cat:"News",des:"Central News Now latest, breaking Central news on ITV News. Videos, stories and updates",uri:"https://centralnewsnow.com/feed",ext:"https://centralnewsnow.com"},
{id:"Chicago Tribune",cat:"News",des:"Chicago Tribune Your source for Chicago breaking news, sports, business, entertainment, weather and traffic.",uri:"https://www.chicagotribune.com/arcio/rss/category/news/breaking/?query=display_date:%5Bnow-2d+TO+now%5D+AND+revision.published:true&sort=display_date:desc#nt=instory-link",ext:"https://www.chicagotribune.com"},
{id:"ABC",cat:"News",des:"ABC Chicago Breaking News covering Weather, Traffic and Sports.",uri:"https://abc7chicago.com/feed",ext:"https://abc7chicago.com"},
{id:"CBS",cat:"News",des:"CBS WBBM Chicago All the Local News and information you need.",uri:"https://chicago.cbslocal.com/feed",ext:"https://chicago.cbslocal.com"},
{id:"Portland Press Herald",cat:"News",des:"Portland Press Herald Serves southern Maine from Portland, Cape Elizabeth, Gorham, Falmouth to Lewiston-Auburn.",uri:"https://www.pressherald.com/feed",ext:"https://www.pressherald.com"},
{id:"NBC",cat:"News",des:"NBC KING Washington Seattle licensed to Seattle, Washington, United States and also serving Tacoma.",uri:"http://rssfeeds.king5.com/king5/home&x=1",ext:"https://www.king5.com"},
{id:"CBS",cat:"News",des:"CBS KTVT Texas Dallas Breaking News, Weather, Traffic, and Sports.",uri:"https://dfw.cbslocal.com/feed",ext:"https://dfw.cbslocal.com"},
{id:"ABC",cat:"News",des:"ABC KTRK Texas Houston Breaking News from Houston and the surrounding neighborhoods.",uri:"https://abc13.com/feed",ext:"https://abc13.com"},
{id:"ABC",cat:"News",des:"ABC KSAT Texas San Antonio Latest News, Weather and Sports.",uri:"https://www.ksat.com/arcio/rss/category/news/national/?size=10",ext:"https://www.ksat.com"},
{id:"New York Sun",cat:"News",des:"The New York Sun was the first successful penny daily newspaper in the United States.",uri:"https://www.nysun.com/rss.xml",ext:"https://www.nysun.com"},
{id:"ABC",cat:"News",des:"ABC KMGB Colorado Denver for Weather, Local, Headlines, and Sports.",uri:"https://www.thedenverchannel.com/news.rss",ext:"https://www.thedenverchannel.com"},
{id:"CBS",cat:"News",des:"CBS KCNC Colorado Denver Denver news, Colorado news, Colorado weather forecasts and sports reports.",uri:"https://denver.cbslocal.com/feed",ext:"https://denver.cbslocal.com"},
{id:"CBS",cat:"News",des:"CBS WWL Louisiana New Orleans dedicated to serving the community through in-depth local news coverage.",uri:"http://rssfeeds.wwltv.com/wwl/local&x=1",ext:"https://www.wwltv.com"},
{id:"NBC",cat:"News",des:"NBC WDSU Louisiana New Orleans Get New Orleans News and Weather from WDSU News.",uri:"https://www.wdsu.com/topstories-rss",ext:"https://www.wdsu.com"},
{id:"ABC",cat:"News",des:"ABC WGNO Louisiana New Orleans for Local and National News and Headlines.",uri:"https://wgno.com/feed",ext:"https://wgno.com"},
{id:"CBS",cat:"News",des:"CBS WJZ Maryland Baltimore serving the greater area of Maryland.",uri:"https://baltimore.cbslocal.com/feed",ext:"https://baltimore.cbslocal.com"},
{id:"NBC",cat:"News",des:"NBC WBAL Maryland Baltimore Get all the latest Baltimore news, weather and sports.",uri:"https://www.wbaltv.com/topstories-rss",ext:"https://www.wbaltv.com"},
{id:"NBC",cat:"News",des:"NBC WKYC Ohio Cleveland NBC affiliate providing the local news, weather, and sports.",uri:"http://rssfeeds.wkyc.com/wkyc/news&x=1",ext:"https://www.wkyc.com"},
{id:"NBC",cat:"News",des:"NBC KGW Oregon Portland provide breaking news, traffic and sports.",uri:"http://rssfeeds.kgw.com/kgw/local&x=1",ext:"https://www.kgw.com"},
{id:"CBS",cat:"News",des:"CBS KOIN Oregon Portland Portland and Vancouver area news and weather stories to make Oregon and Southwest Washington a better place to live.",uri:"https://www.koin.com/feed",ext:"https://www.koin.com"},
{id:"CBS",cat:"News",des:"CBS KYW Pennsylvania Philadelphia Eyewitness News, Sports, Weather, and Traffic.",uri:"https://philadelphia.cbslocal.com/feed",ext:"https://philadelphia.cbslocal.com"},
{id:"ABC",cat:"News",des:"ABC WPVI Pennsylvania Philadelphia source for breaking news and live streaming video online.",uri:"https://6abc.com/feed",ext:"https://6abc.com"},
{id:"CBS",cat:"News",des:"CBS KENS Texas San Antonio television station which works San Antonio, Texas Valley cities.",uri:"http://rssfeeds.kens5.com/kens5/local-news&x=1",ext:"https://www.kens5.com"},
{id:"Salt Lake Tribune",cat:"News",des:"The Salt Lake Tribune covers news, entertainment, sports and faith for Salt Lake City and the state of Utah.",uri:"https://www.sltrib.com/arcio/rss/category/news/nation-world/?summary=true",ext:"https://www.sltrib.com/news/nation-world"},
{id:"CBS",cat:"News",des:"CBS WUSA Washington D.C. licensed to the Capital City of Washington, District of Columbia.",uri:"http://rssfeeds.wusa9.com/wusa-news&x=1",ext:"https://wusa9.com"},
{id:"NBC",cat:"News",des:"NBC WVTM Alabama Birmingham broadcasts across Central Alabama.",uri:"https://www.wvtm13.com/topstories-rss",ext:"https://www.wvtm13.com"},
{id:"CBS",cat:"News",des:"CBS WIAT Alabama Birmingham Local, Weather, and Live.",uri:"https://www.cbs42.com/feed",ext:"https://www.cbs42.com"},
{id:"ABC",cat:"News",des:"ABC WDHN Alabama Dothan your source for News, Weather and Sports.",uri:"https://www.dothanfirst.com/feed",ext:"https://www.dothanfirst.com"},
{id:"CBS",cat:"News",des:"CBS WTVY Alabama Dothan News, Your News Leader, Wiregrass.",uri:"https://www.wtvy.com/rss",ext:"https://www.wtvy.com"},
{id:"CBS",cat:"News",des:"CBS WHNT Alabama Huntsville North Alabama's News Leader.",uri:"https://whnt.com/feed",ext:"https://whnt.com"},
{id:"CBS",cat:"News",des:"CBS WKRG Alabama Mobile, Pensacola, Baldwin County and the rest of the Golf Coast.",uri:"https://www.wkrg.com/feed",ext:"https://www.wkrg.com"},
{id:"ABC",cat:"News",des:"ABC WNCF Alabama Montgomery Local late Breaking News.",uri:"https://www.alabamanews.net/feed",ext:"https://www.alabamanews.net"},
{id:"CBS",cat:"News",des:"CBS WAKA Alabama Selma Montgomery television station for Central Alabama River Region.",uri:"https://www.alabamanews.net/feed",ext:"https://www.alabamanews.net"},
{id:"ABC",cat:"News",des:"ABC KHBS Arkansas Fort Smith Trending and Latest Headlines.",uri:"https://www.4029tv.com/topstories-rss",ext:"https://www.4029tv.com"},
{id:"NBC",cat:"News",des:"NBC KVOA Arizona Tucson’s NBC affiliate, KVOA serves more than a million people.",uri:"https://kvoa.com/feed",ext:"https://kvoa.com"},
{id:"NBC",cat:"News",des:"NBC KYMA Arizona television station licensed to Yuma, Arizona.",uri:"https://kyma.com/feed",ext:"https://kyma.com"},
{id:"NBC",cat:"News",des:"NBC KPNX Arizona Phoenix Updates and Stories, News, and Weather.",uri:"http://rssfeeds.12news.com/kpnx/local&x=1",ext:"http://www.12news.com"},
{id:"NBC",cat:"News",des:"NBC KTVE Arkansas El Dorado Your Southern Arkansas Local News Leader.",uri:"https://www.myarklamiss.com/feed",ext:"https://www.myarklamiss.com"},
{id:"FOX",cat:"News",des:"FOX KFTA Arkansas Fort Smith overs the rapidly growing and vibrant Northwest Arkansas and River Valley.",uri:"https://www.nwahomepage.com/feed",ext:"https://www.nwahomepage.com"},
{id:"CBS",cat:"News",des:"CBS KFSM Arkansas Fort Smith serving the Arkansas River Valley and Northwest Arkansas.",uri:"https://5newsonline.com/feed",ext:"https://5newsonline.com"},
{id:"NBC",cat:"News",des:"NBC KARK Arkansas Little Rock your source for local weather, news and sports.",uri:"https://www.kark.com/feed",ext:"https://www.kark.com"},
{id:"CBS",cat:"News",des:"CBS KTHV Arkansas Little Rock the day's news, providing important weather information, or telling a story.",uri:"http://rssfeeds.thv11.com/kthv/local&x=1",ext:"https://www.thv11.com"},
{id:"ABC",cat:"News",des:"ABC KRDO Colorado Springs Latest News Local and National.",uri:"https://krdo.com/feed",ext:"https://krdo.com"},
{id:"CBS",cat:"News",des:"CBS KREX Colorado Grand Junction The Latest News and Updates in Local News brought to you by the team at KREX.",uri:"https://www.westernslopenow.com/feed",ext:"https://www.westernslopenow.com"},
{id:"NBC",cat:"News",des:"NBC KUSA Colorado News Join the photographers and reporters of as they explore every corner of our state.",uri:"http://rssfeeds.9news.com/kusa/home&x=1",ext:"http://www.9news.com"},
{id:"ABC",cat:"News",des:"ABC WTNH Connecticut Hartford New Haven Local and National Headlines and News.",uri:"https://www.wtnh.com/feed",ext:"https://www.wtnh.com"},
{id:"ABC",cat:"News",des:"ABC Chicago Breaking News covering Weather, Traffic and Sports.",uri:"https://abc7chicago.com/feed",ext:"https://abc7chicago.com"},
{id:"CBS",cat:"News",des:"CBS WINK Florida Fort Myers one of a handful of TV stations today to have locally-based ownership.",uri:"https://www.winknews.com/feed",ext:"https://www.winknews.com"},
{id:"ABC",cat:"News",des:"ABC WTLV Florida Jacksonville up to the minute Local Late Breaking News.",uri:"http://rssfeeds.firstcoastnews.com/wtlv/firstcoastnews-topstories&x=1",ext:"http://www.firstcoastnews.com"},
{id:"CBS",cat:"News",des:"CBS WKMG Florida Orlando Local news, headlines, national news, videos, and more.",uri:"https://www.clickorlando.com/arcio/rss/category/news/?size=10",ext:"https://www.clickorlando.com"},
{id:"ABC",cat:"News",des:"ABC WMBB Florida Panama City We tell local Panama City news & weather stories.",uri:"https://www.mypanhandle.com/feed",ext:"https://www.mypanhandle.com"},
{id:"CBS",cat:"News",des:"CBS WTSP Florida St. Petersburg Tampa Bay and Sarasota area's best news, weather, and traffic.",uri:"http://rssfeeds.wtsp.com/wtsp/home&x=1",ext:"https://www.wtsp.com"},
{id:"ABC",cat:"News",des:"ABC WPBF Florida West Palm Beach is your source for the latest local headlines and live alerts.",uri:"https://www.wpbf.com/topstories-rss",ext:"https://www.wpbf.com"},
{id:"NBC",cat:"News",des:"NBC WESH Florida television station serving Orlando, Florida, United States that is licensed to Daytona Beach.",uri:"https://www.wesh.com/topstories-rss",ext:"https://www.wesh.com"},
{id:"NBC",cat:"News",des:"NBC WFLA Florida Get your local news from News Channel 8, On Your Side for Tampa Bay, St. Petersburg and central Florida.",uri:"https://www.wfla.com/feed",ext:"https://www.wfla.com"},
{id:"CBS",cat:"News",des:"CBS WSWG Georgia Albany You can watch local news, daytime shows, primetime shows, late night programming on WSWG.",uri:"https://www.southgatv.com/feed",ext:"https://www.southgatv.com"},
{id:"ABC",cat:"News",des:"ABC WJBF Georgia Augsusta Breaking News, Weather, and Sports.",uri:"https://www.wjbf.com/feed",ext:"https://www.wjbf.com"},
{id:"CBS",cat:"News",des:"CBS WRBL Georgia Columbus serving the Chattahoochee Valley of west-central Georgia and east-central Alabama.",uri:"https://www.wrbl.com/feed",ext:"https://www.wrbl.com"},
{id:"CBS",cat:"News",des:"CBS WMAZ Georgia Macon has been affiliated with the CBS Television Network since the station signed on 60 years ago.",uri:"http://rssfeeds.13wmaz.com/wmaz/headlines/local&x=1",ext:"https://www.13wmaz.com"},
{id:"ABC",cat:"News",des:"ABC WJCL Georgia Savannah is your source for the Latest Local Headlines.",uri:"https://www.wjcl.com/topstories-rss",ext:"https://www.wjcl.com"},
{id:"NBC",cat:"News",des:"NBC WLTZ Georgia Putting you first with news, weather, and sports in Columbus, Phoenix City, Auburn, Opelika, and the surrounding area.",uri:"https://www.wltz.com/feed",ext:"https://www.wltz.com"},
{id:"NBC",cat:"News",des:"NBC WMGT Georgia the second commercial station started in the Middle Georgia market.",uri:"https://41nbc.com/feed",ext:"https://41nbc.com"},
{id:"NBC",cat:"News",des:"NBC WSAV Georgia faithfully served Savannah, Statesboro, Hilton Head and our many neighbors.",uri:"https://www.wsav.com/feed",ext:"https://www.wsav.com"},
{id:"CBS",cat:"News",des:"CBS KIDK Idaho Falls licensed to Idaho Falls, Idaho, United States and also serving Pocatello.",uri:"https://localnews8.com/feed",ext:"https://localnews8.com"},
{id:"ABC",cat:"News",des:"ABC KIFI Idaho Falls News Press and Gazette Company.",uri:"https://localnews8.com/feed",ext:"https://localnews8.com"},
{id:"ABC",cat:"News",des:"ABC WSIL Southern Illinois providing breaking news, sports and weather information.",uri:"https://wsiltv.com/feed",ext:"https://wsiltv.com"},
{id:"CBS",cat:"News",des:"CBS WCIA Illinois Champaign Your Central Illinois News, Weather, and Sports Leader.",uri:"https://www.wcia.com/feed",ext:"https://www.wcia.com"},
{id:"ABC",cat:"News",des:"ABC WQAD Illinois Moline serving the Quad Cities of West-Central Illinois.",uri:"https://wqad.com/feed",ext:"https://wqad.com"},
{id:"CBS",cat:"News",des:"CBS WMBD Illinois Peoria We tell local Peoria news & weather stories.",uri:"https://www.centralillinoisproud.com/feed",ext:"https://www.centralillinoisproud.com"},
{id:"ABC",cat:"News",des:"ABC WEEK Illinois Peoria All the News for your needs.",uri:"https://week.com/feed",ext:"https://week.com"},
{id:"ABC",cat:"News",des:"ABC WTVO Illinois Rockford local Rockford news & weather stories.",uri:"https://www.mystateline.com/feed",ext:"https://www.mystateline.com"},
{id:"ABC",cat:"News",des:"ABC WEHT Illinois serving the Tri states of Indiana, Kentucky, and Illinois.",uri:"https://www.tristatehomepage.com/feed",ext:"https://www.tristatehomepage.com"},
{id:"NBC",cat:"News",des:"NBC WGEM Illinois Quincy the dominant #1 NBC affiliate in Quincy, Illinois.",uri:"https://wgem.com/feed",ext:"https://wgem.com"},
{id:"NBC",cat:"News",des:"NBC WREX Illinois Rockford live streaming online is an NBC-affiliated television station that works in Rockford, Illinois.",uri:"https://wrex.com/feed",ext:"https://wrex.com"},
{id:"CBS",cat:"News",des:"CBS WHBF Illinois Rock Island The Latest News and Updates in Local News brought to you by the team at WHBF.",uri:"https://www.ourquadcities.com/feed",ext:"https://www.ourquadcities.com"},
{id:"ABC",cat:"News",des:"ABC WPTA Fort Wanye Indiana your source for breaking news and severe weather coverage, plus news, weather and sports.",uri:"https://wpta21.com/feed",ext:"https://wpta21.com/"},
{id:"NBC",cat:"News",des:"NBC WPTA Fort Wayne Indiana Latest News, Sports, Local, and Weather.",uri:"https://fortwaynesnbc.com/feed",ext:"https://fortwaynesnbc.com"},
{id:"CBS",cat:"News",des:"CBS WTTV Indiana Indianapolis news, weather, sports, contests, and community events.",uri:"https://cbs4indy.com/feed",ext:"https://cbs4indy.com"},
{id:"NBC",cat:"News",des:"NBC WTHR Indiana Indianapolis #1 news station and your source for Weather, radar, traffic, and sports.",uri:"https://www.wthr.com/feed/public/breaking-news.xml",ext:"https://www.wthr.com"},
{id:"ABC",cat:"News",des:"ABC WBND South Bend Indiana the most up to minute Local and National News.",uri:"https://www.abc57.com/rss",ext:"https://www.abc57.com"},
{id:"ABC",cat:"News",des:"ABC WBND South Bend Indiana serving Northern Indiana and the southern portion of Western Michigan.",uri:"https://wsbt.com/news/local.rss",ext:"https://wsbt.com"},
{id:"ABC",cat:"News",des:"ABC WAWV Indiana Terra Haute a full service television station.",uri:"https://www.mywabashvalley.com/feed",ext:"https://www.mywabashvalley.com"},
{id:"NBC",cat:"News",des:"NBC KWQC Iowa Davenport serving the Quad Cities area of Southeastern Iowa and Northwestern Illinois.",uri:"https://www.kwqc.com/templates/2015_XML_FEED?placement=/content/news",ext:"https://www.kwqc.com"},
{id:"CBS",cat:"News",des:"CBS KCCI Iowa Des Moines KCCI news team brings you the best in local coverage and all the top stories from across the state.",uri:"https://www.kcci.com/topstories-rss",ext:"https://www.kcci.com"},
{id:"NBC",cat:"News",des:"NBC WHO Iowa branded on-air as WHO-HD, is an NBC - affiliated television station licensed to Des Moines, Iowa.",uri:"https://whotv.com/feed",ext:"https://whotv.com"},
{id:"NBC",cat:"News",des:"NBC KYOU Iowa affiliated television station for the area of Southeastern Iowa and Northeastern Missouri.",uri:"https://www.kyoutv.com/feed",ext:"https://www.kyoutv.com"},
{id:"NBC",cat:"News",des:"NBC KTIV Iowa Our mission is to provide you with the latest news, weather and sports in Siouxland.",uri:"https://ktiv.com/feed",ext:"https://ktiv.com"},
{id:"NBC",cat:"News",des:"NBC KWWL eastern Iowa's homepage for breaking news, severe weather, video and sports, with newsrooms in Waterloo, Dubuque, Cedar Rapids and Iowa City.",uri:"https://kwwl.com/feed",ext:"https://kwwl.com"},
{id:"ABC",cat:"News",des:"ABC WOI Iowa Des Moines local Des Moines news & weather stories.",uri:"https://www.weareiowa.com/feed",ext:"https://www.weareiowa.com"},
{id:"NBC",cat:"News",des:"NBC KSNW Kansas Wichita We tell local Kansas news & weather stories. We are Here for You.",uri:"https://www.ksn.com/feed",ext:"https://www.ksn.com"},
{id:"NBC",cat:"News",des:"NBC KSNT Kansas We tell local Topeka and Northeast Kansas News & Weather stories. Local News That Matters.",uri:"https://www.ksnt.com/feed",ext:"https://www.ksnt.com"},
{id:"NBC",cat:"News",des:"NBC WNKY Kentucky Bowling Green News, Weather & Community.",uri:"https://www.wnky.com/feed",ext:"https://www.wnky.com"},
{id:"ABC",cat:"News",des:"ABC WTVQ Kentucky Lexington Local Late Breaking News.",uri:"https://www.wtvq.com/feed",ext:"https://www.wtvq.com"},
{id:"ABC",cat:"News",des:"ABC WHAS Kentucky Louisville is built on journalistic excellence and a commitment to improve the communities.",uri:"http://rssfeeds.whas11.com/whas/local&x=1",ext:"http://www.whas11.com"},
{id:"CBS",cat:"News",des:"CBS WLKY Kentucky Louisville Get Louisville news and weather from WLKY.",uri:"https://www.wlky.com/topstories-rss",ext:"https://www.wlky.com"},
{id:"ABC",cat:"News",des:"ABC KLAX Louisiana Alexandria was launched on March 3, link 1983 originally as an independent station.",uri:"http://klax-tv.com/feed",ext:"http://klax-tv.com"},
{id:"NBC",cat:"News",des:"NBC WVLA Louisiana Baton Rouge Local 33 News is a NBC News affiliate serving Baton Rouge and the surrounding areas.",uri:"https://www.brproud.com/feed",ext:"https://www.brproud.com"},
{id:"CBS",cat:"News",des:"CBS KLFY Louisiana Lafayette we do what we do to make Lafayette, and the rest of Acadiana a better place to live.",uri:"https://www.klfy.com/feed/",ext:"https://www.klfy.com"},
{id:"NBC",cat:"News",des:"NBC KADN Louisiana Lafayette a mix of News, Weather, Sports, and Entertainment with a Focus on Families and the Community.",uri:"https://kadn.com/feed",ext:"https://kadn.com"},
{id:"NBC",cat:"News",des:"NBC WMTV Maine Portland We are a local Internet TV Station dedicated to serving our community with local news.",uri:"https://www.wmtw.com/topstories-rss",ext:"https://www.wmtw.com"},
{id:"Baltimore Sun",cat:"News",des:"Baltimore Sun Your source for breaking news, sports, business, entertainment, weather and traffic.",uri:"https://www.baltimoresun.com/arcio/rss/category/latest/?query=display_date:%5Bnow-2d+TO+now%5D+AND+revision.published:true&sort=display_date:desc#nt=instory-link",ext:"https://www.baltimoresun.com"},
{id:"ABC",cat:"News",des:"ABC WMDT Marlyand Salisbury for News, Traffic, Sports, and Entertainment.",uri:"https://www.wmdt.com/feed",ext:"https://www.wmdt.com"},
{id:"CBS",cat:"News",des:"CBS WBKB Michigan Alpena For all your local news, sports, and weather updates.",uri:"http://www.wbkb11.com/feed",ext:"http://www.wbkb11.com"},
{id:"NBC",cat:"News",des:"NBC WCSH Maine Portland serving Southern Maine as well as Eastern and Northern New Hampshire.",uri:"http://rssfeeds.wcsh6.com/newscentermaine/news&x=1",ext:"https://www.newscentermaine.com"},
{id:"NBC",cat:"News",des:"NBC WWLP Massachussetts Springfield We tell local Springfield news & weather stories.",uri:"https://www.wwlp.com/feed",ext:"https://www.wwlp.com"},
{id:"CBS",cat:"News",des:"CBS WWJ Michigan Detroit BS owned-and-operated television station licensed to Detroit, Michigan.",uri:"https://detroit.cbslocal.com/feed",ext:"https://detroit.cbslocal.com"},
{id:"NBC",cat:"News",des:"NBC WDIV Michigan Detroit Local 4 News, headlines, weather, and sports.",uri:"https://www.clickondetroit.com/arcio/rss/category/news/?size=10",ext:"https://www.clickondetroit.com"},
{id:"ABC",cat:"News",des:"ABC WJRT Michigan Flint Weather, News, Sports, and more.",uri:"https://www.abc12.com/templates/2015_XML_FEED?placement=/content/news",ext:"https://www.abc12.com"},
{id:"CBS",cat:"News",des:"CBS WJMN Michigan Escanaba serving the Central and Western Upper Peninsula of Michigan.",uri:"https://www.upmatters.com/feed",ext:"https://www.upmatters.com"},
{id:"NBC",cat:"News",des:"NBC WOOD Michigan Grand Rapids we do what we do to make Grand Rapids & the rest of Michigan a better place to live.",uri:"https://www.woodtv.com/feed",ext:"https://www.woodtv.com"},
{id:"ABC",cat:"News",des:"ABC WZZM Michigan Grand Rapids Late Breaking News and Headlines.",uri:"http://rssfeeds.wzzm13.com/wzzm13-news&x=1",ext:"http://www.wzzm13.com"},
{id:"ABC",cat:"News",des:"ABC WBUP Michigan Marquette serving the greater area of Michigan.",uri:"https://abc10up.com/feed",ext:"https://abc10up.com"},
{id:"ABC",cat:"News",des:"ABC WLNS Michigan Lansing driving force behind Mid-Michigan's businesses, lifestyle and culture.",uri:"https://www.wlns.com/feed",ext:"https://www.wlns.com"},
{id:"CBS",cat:"News",des:"CBS WWTV Michigan Cadillac Traverse City News, Weather, Sports, Traffic.",uri:"https://www.9and10news.com/feed",ext:"https://www.9and10news.com"},
{id:"NBC",cat:"News",des:"NBC KBJR Minnesota Duluth Your Weather Authority has a free news.",uri:"https://kbjr6.com/feed",ext:"https://kbjr6.com"},
{id:"CBS",cat:"News",des:"CBS WCCO Minnesota Minneapolis All the local news and information you need – plus other fun stuff – from the team at WCCO.",uri:"https://minnesota.cbslocal.com/feed",ext:"https://minnesota.cbslocal.com"},
{id:"NBC",cat:"News",des:"NBC KARE Minnesota Minneapolis erves up a fresh take for a new day with the latest news and weather.",uri:"http://rssfeeds.kare11.com/kare11/topstories&x=1",ext:"http://www.kare11.com"},
{id:"NBC",cat:"News",des:"NBC KTTC Minnesota Rochester The area's most watched news team provides the latest news, weather and sports on-air and online.",uri:"https://kttc.com/feed",ext:"https://kttc.com"},
{id:"Star Tribune",cat:"News",des:"Minneapolis Star Tribune the largest newspaper in Minnesota.",uri:"http://www.startribune.com/rss",ext:"http://www.startribune.com"},
{id:"CBS",cat:"News",des:"CBS WCBI Mississippi Columbus Tupelo serving northeastern Mississippi and northwestern Alabama.",uri:"https://www.wcbi.com/feed",ext:"https://www.wcbi.com"},
{id:"ABC",cat:"News",des:"ABC WAPT Mississippi Jackson News The One To Watch.",uri:"https://www.wapt.com/topstories-rss",ext:"https://www.wapt.com"},
{id:"CBS",cat:"News",des:"CBS WJTV Mississippi Jackson Local Mississippi breaking news and weather from CBS 12 News WJTV.",uri:"https://www.wjtv.com/feed",ext:"https://www.wjtv.com"},
{id:"ABC",cat:"News",des:"ABC KMIZ Missouri Columbia Jefferson City News, Weather, and Sports.",uri:"https://abc17news.com/feed",ext:"https://abc17news.com"},
{id:"NBC",cat:"News",des:"NBC WXXV Mississippi Biloxi television station licensed to Gulfport and serving the Gulf Coast.",uri:"https://www.wxxv25.com/feed",ext:"https://www.wxxv25.com"},
{id:"ABC",cat:"News",des:"ABC KODE Missouri Joplin an ABC-affiliated television station licensed to Joplin, Missouri.",uri:"https://www.fourstateshomepage.com/feed",ext:"https://www.fourstateshomepage.com"},
{id:"ABC",cat:"News",des:"ABC KMBC Missouri Kansas City your source for the latest local headlines and live alerts.",uri:"https://www.kmbc.com/topstories-rss",ext:"https://www.kmbc.com"},
{id:"CBS",cat:"News",des:"CBS KOLR Missouri Springfield offering Local News, Weather, Sports, and Traffic.",uri:"https://www.ozarksfirst.com/feed",ext:"https://www.ozarksfirst.com"},
{id:"NBC",cat:"News",des:"NBC KSDK Missouri St Louis On Your Side has a rich broadcast heritage.",uri:"http://rssfeeds.ksdk.com/ksdk-usworldnews&x=1",ext:"http://www.ksdk.com"},
{id:"ABC",cat:"News",des:"ABC KSVI Montana Billings a community portal powered by ABC.",uri:"https://www.yourbigsky.com/feed",ext:"https://www.yourbigsky.com"},
{id:"NBC",cat:"News",des:"NBC KXGN Montana Glendive News Stories and Videos.",uri:"http://web.kxgn.com/feed",ext:"http://web.kxgn.com"},
{id:"ABC",cat:"News",des:"ABC KETV Nebraska Omaha the latest Omaha News, Sports and Weather.",uri:"https://www.ketv.com/topstories-rss",ext:"https://www.ketv.com"},
{id:"NBC",cat:"News",des:"NBC KSNB Nebraska Lincoln affiliated television station licensed to Superior, Nebraska.",uri:"https://www.ksnblocal4.com/rss",ext:"https://www.ksnblocal4.com"},
{id:"NBC",cat:"News",des:"NBC KNEP Nebraska Scottsbluff News, Weather, and Stories.",uri:"https://www.ksnblocal4.com/rss",ext:"https://www.ksnblocal4.com"},
{id:"ABC",cat:"News",des:"ABC WMUR New Hampshire Manchesters most reliable source for Breaking News.",uri:"https://www.wmur.com/topstories-rss",ext:"https://www.wmur.com"},
{id:"ABC",cat:"News",des:"ABC KOAT New Mexico Albuquerque get all the latest Local and National News.",uri:"https://www.koat.com/topstories-rss",ext:"https://www.koat.com"},
{id:"CBS",cat:"News",des:"CBS KRQE New Mexico Albuquerque We are local reporting you can trust, providing the latest news and accurate weather forecasts.",uri:"https://www.krqe.com/feed",ext:"https://www.krqe.com"},
{id:"ABC",cat:"News",des:"ABC KVIA New Mexico Las Cruces Breaking News Daily updates and National Headlines.",uri:"https://kvia.com/feed",ext:"https://kvia.com"},
{id:"ABC",cat:"News",des:"ABC WTEN New York Albany serving New York Capital District as well as Berkshire County, Massachusetts.",uri:"https://www.news10.com/feed",ext:"https://www.news10.com"},
{id:"ABC",cat:"News",des:"ABC WIVT New York Binghampton Latest News and Updates in News brought to you by the team at WIVT.",uri:"https://www.binghamtonhomepage.com/feed",ext:"https://www.binghamtonhomepage.com"},
{id:"CBS",cat:"News",des:"CBS WBNG New York Binghampton Television Market which serves the Southern Tier of New York State.",uri:"https://wbng.com/feed",ext:"https://wbng.com"},
{id:"CBS",cat:"News",des:"CBS WIVB New York Buffalo The station is owned by Nexstar Media Group, as part of a duopoly with CW affiliate WNLO.",uri:"https://www.wivb.com/feed",ext:"https://www.wivb.com"},
{id:"NBC",cat:"News",des:"NBC WGRZ New York Buffalo for breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.",uri:"http://rssfeeds.wgrz.com/wgrz/headlines/top-stories&x=1",ext:"http://www.wgrz.com"},
{id:"NBC",cat:"News",des:"NBC WETM New York Elmira The Latest News and Updates in news brought to you by the team at WETM.",uri:"https://www.mytwintiers.com/feed",ext:"https://www.mytwintiers.com"},
{id:"NBC",cat:"News",des:"NBC WPTZ New York Plattsburge your source for the latest local headlines.",uri:"https://www.mynbc5.com/topstories-rss",ext:"https://www.mynbc5.com"},
{id:"CBS",cat:"News",des:"CBS WROC New York Rochester CBS - affiliated television station licensed to Rochester, New York.",uri:"https://www.rochesterfirst.com/feed",ext:"https://www.rochesterfirst.com"},
{id:"ABC",cat:"News",des:"ABC WSYR New York Syracuse local Syracuse news & weather stories.",uri:"https://www.localsyr.com/feed",ext:"https://www.localsyr.com"},
{id:"ABC",cat:"News",des:"ABC WUTR New York Utica making Utica & the rest of central New York a better place to live.",uri:"https://www.cnyhomepage.com/feed",ext:"https://www.cnyhomepage.com"},
{id:"ABC",cat:"News",des:"ABC WWTI New York Waterton serving the public with News and Headlines.",uri:"https://www.informnny.com/feed",ext:"https://www.informnny.com"},
{id:"NBC",cat:"News",des:"NBC WVNC New York Waterton News, Weather, and Sports for Watertown, New York.",uri:"https://www.nbcwatertown.com/feed",ext:"https://www.nbcwatertown.com"},
{id:"NBC",cat:"News",des:"NBC WCNC North Carolina Charlotte Looking Out For You. It's more than just our slogan; it's a candid commitment to our viewers.",uri:"http://rssfeeds.wcnc.com/wcnc/home&x=1",ext:"https://www.wcnc.com"},
{id:"CBS",cat:"News",des:"CBS WFMY North Carolina Greensboro serving the Piedmont Triad region Greensboro, Winston-Salem, High Point.",uri:"http://rssfeeds.wfmynews2.com/wfmynews2-local&x=1",ext:"https://www.wfmynews2.com"},
{id:"CBS",cat:"News",des:"CBS WNCT North Carolina Greenville serving Eastern North Carolina 's Inner Banks region.",uri:"https://www.wnct.com/feed",ext:"https://www.wnct.com"},
{id:"CBS",cat:"News",des:"CBS WWAY North Carolina Wilmington licensed to Wilmington, North Carolina, United States and serving the Cape Fear region.",uri:"https://www.wwaytv3.com/feed",ext:"https://www.wwaytv3.com"},
{id:"CBS",cat:"News",des:"CBS WNCN North Carolina Raleigh serving the Triangle region, Durham, Chapel Hill, Fayetteville.",uri:"https://www.cbs17.com/feed",ext:"https://www.cbs17.com"},
{id:"CBS",cat:"News",des:"CBS WWAY North Carolina Wilmington Local Up to the Minute Late Breaking News.",uri:"https://www.wwaytv3.com/feed",ext:"https://www.wwaytv3.com"},
{id:"NBC",cat:"News",des:"NBC WXII North Carolina Wilmington Piedmont Triad's most reliable source for breaking news.",uri:"https://www.wxii12.com/topstories-rss",ext:"https://www.wxii12.com"},
{id:"CBS",cat:"News",des:"CBS KXMB North Dakota Bismarck Your Eye on Dakota.",uri:"https://www.kxnet.com/feed",ext:"https://www.kxnet.com"},
{id:"NBC",cat:"News",des:"NBC KVLY North Dakota Fargo The station is most notable for its broadcast tower which is the fourth-tallest above-ground structure in the world.",uri:"https://www.valleynewslive.com/rss",ext:"https://www.valleynewslive.com"},
{id:"NBC",cat:"News",des:"NBC WLWT Ohio Cincinnati most reliable source for breaking news.",uri:"https://www.wlwt.com/topstories-rss",ext:"https://www.wlwt.com"},
{id:"NBC",cat:"News",des:"NBC WCMH Ohio Columbus Ohio's top rated source for breaking news and live streaming video online.",uri:"https://www.nbc4i.com/feed",ext:"https://www.nbc4i.com"},
{id:"NBC",cat:"News",des:"NBC WDTN Ohio Dayton television station for the Miami Valley in Ohio.",uri:"https://www.wdtn.com/feed",ext:"https://www.wdtn.com"},
{id:"ABC",cat:"News",des:"ABC WYTV Ohio Youngstown We Believe in This Valley.",uri:"https://www.wytv.com/feed",ext:"https://www.wytv.com"},
{id:"CBS",cat:"News",des:"CBS WKBN Ohio Youngstown watch local news, daytime shows, primetime shows, and late night programming.",uri:"https://www.wkbn.com/feed",ext:"https://www.wkbn.com"},
{id:"NBC",cat:"News",des:"NBC WHIZ Ohio Zanesville NBC-affiliated television station licensed to Zanesville, Ohio, United States.",uri:"https://whiznews.com/feed",ext:"https://whiznews.com"},
{id:"ABC",cat:"News",des:"ABC KOCO Oklahoma City reliable Local and National News.",uri:"https://www.koco.com/topstories-rss",ext:"https://www.koco.com"},
{id:"NBC",cat:"News",des:"NBC KFOR Oklahoma City is an entertainment company based out of New Orleans, Louisiana.",uri:"https://kfor.com/feed",ext:"https://kfor.com"},
{id:"NBC",cat:"News",des:"NBC KTVZ Oregon Bend Stories, News, Sports, and Weather.",uri:"https://ktvz.com/feed",ext:"https://ktvz.com"},
{id:"NBC",cat:"News",des:"NBC KOTI Oregon Medford Klamath Falls Latest News, Weather Updates, and Sports Reporting.",uri:"https://kobi5.com/feed",ext:"https://kobi5.com"},
{id:"CBS",cat:"News",des:"CBS WTAJ Pennsylvania Altoona serving West-Central Pennsylvania.",uri:"https://www.wearecentralpa.com/feed",ext:"https://www.wearecentralpa.com"},
{id:"ABC",cat:"News",des:"ABC WJET Pennsylvania Erie Bringing You News, Weather, Sports, and Entertainment.",uri:"https://www.yourerie.com/feed",ext:"https://www.yourerie.com"},
{id:"ABC",cat:"News",des:"ABC WHTM Pennsylvania Harrisburg breaking news, latest headlines, severe weather, sports, and traffic.",uri:"https://www.abc27.com/feed",ext:"https://www.abc27.com"},
{id:"NBC",cat:"News",des:"NBC WGAL Pennsylvania Lancaster Stay in the know with the top stories of the day. Get all the latest Harrisburg, Lancaster and York news.",uri:"https://www.wgal.com/topstories-rss",ext:"https://www.wgal.com"},
{id:"ABC",cat:"News",des:"ABC WTAE Pennsylvania Pittsburgh Stay in the know with the latest Pittsburgh news, weather and sports.",uri:"https://www.wtae.com/topstories-rss",ext:"https://www.wtae.com"},
{id:"CBS",cat:"News",des:"CBS KDKA Pennsylvania Pittsburgh KDKA in Pittsburgh, most often cited as the first radio outlet in the United States.",uri:"https://pittsburgh.cbslocal.com/feed",ext:"https://pittsburgh.cbslocal.com"},
{id:"ABC",cat:"News",des:"ABC WNEP Pennsylvania Scranton News, Weather and Sports Proud to Serve Northeastern and Central Pennsylvania.",uri:"https://wnep.com/feed",ext:"https://wnep.com"},
{id:"CBS",cat:"News",des:"CBS WYOU Pennsylvania Scranton affiliated television station licensed to Scranton, Pennsylvania, also serving Wilkes-Barre.",uri:"https://www.pahomepage.com/feed",ext:"https://www.pahomepage.com"},
{id:"NBC",cat:"News",des:"NBC WBRE Pennsylvania Wilkes Barre Eye Witness News, Sports, Traffic, and Weather.",uri:"https://www.pahomepage.com/feed",ext:"https://www.pahomepage.com"},
{id:"CBS",cat:"News",des:"CBS WPRI Rhode Island Providence Watch the latest CBS News coverage LIVE right here.",uri:"https://www.wpri.com/feed",ext:"https://www.wpri.com"},
{id:"NBC",cat:"News",des:"NBC WCBD South Carolina Charleston Local News and Weather.",uri:"https://www.counton2.com/feed",ext:"https://www.counton2.com"},
{id:"ABC",cat:"News",des:"ABC WOLO South Carolina Colombia Serving as Columbia’s innovative television station since 1953.",uri:"https://www.abccolumbia.com/feed",ext:"https://www.abccolumbia.com"},
{id:"CBS",cat:"News",des:"CBS WLTX South Carolina Colombia WLTX is the 2nd oldest continuously operating TV station in South Carolina.",uri:"http://rssfeeds.wltx.com/wltx-local&x=1",ext:"https://www.wltx.com"},
{id:"NBC",cat:"News",des:"NBC WYFF South Carolina Greenville News Coverage, Sports, Traffic and, Weather.",uri:"https://www.wyff4.com/topstories-rss",ext:"https://www.wyff4.com"},
{id:"CBS",cat:"News",des:"CBS WBTW South Carolina Myrtle Beach The Latest News and Updates in brought to you by the team at WBTW.",uri:"https://www.wbtw.com/feed",ext:"https://www.wbtw.com"},
{id:"CBS",cat:"News",des:"CBS WSPA South Carolina Spartanburg Greenville News, weather and sports for Greenville, Spartanburg, Anderson, and Pickens, SC and Asheville, Hendersonville, NC.",uri:"https://www.wspa.com/feed",ext:"https://www.wspa.com"},
{id:"NBC",cat:"News",des:"NBC KNBN South Dakota Rapid City Local news from NewsCenter1.",uri:"https://www.newscenter1.tv/feed",ext:"https://www.newscenter1.tv"},
{id:"CBS",cat:"News",des:"CBS KELO South Dakota Sioux Falls KELOLAND News, Weather, Sports for Sioux Falls, South Dakota, northwest Iowa and southwest Minnesota.",uri:"https://www.keloland.com/feed",ext:"https://www.keloland.com"},
{id:"CBS",cat:"News",des:"CBS WDEF Tennessee Chattanooga Live Late Breaking News and Updates.",uri:"https://wdef.com/feed",ext:"https://wdef.com"},
{id:"ABC",cat:"News",des:"ABC WBBJ Tennessee Jackson Local News for the greater Tennessee.",uri:"https://www.wbbjtv.com/feed",ext:"https://www.wbbjtv.com"},
{id:"ABC",cat:"News",des:"ABC WJHL Tennessee Johnson City the source for breaking local, weather and sports news in the Tri-Cities.",uri:"https://www.wjhl.com/feed",ext:"https://www.wjhl.com"},
{id:"ABC",cat:"News",des:"ABC WATE Tennessee Knoxville On Your Side provides the best latest news, weather and sports coverage.",uri:"https://www.wate.com/feed",ext:"https://www.wate.com"},
{id:"ABC",cat:"News",des:"ABC WATN Tennessee Memphis We tell Local Memphis News and Weather Stories.",uri:"https://www.localmemphis.com/feed",ext:"https://www.localmemphis.com"},
{id:"CBS",cat:"News",des:"CBS WREG Tennessee Memphis The channel is certified to Memphis, United States.",uri:"https://wreg.com/feed",ext:"https://wreg.com"},
{id:"ABC",cat:"News",des:"ABC WKRN Tennessee Nashville we do what we do to make Nashville & Tennessee a better place to live.",uri:"https://www.wkrn.com/feed",ext:"https://www.wkrn.com"},
{id:"NBC",cat:"News",des:"NBC KRBC Texas Abilene the station is owned by Mission Broadcasting.",uri:"https://www.bigcountryhomepage.com/feed",ext:"https://www.bigcountryhomepage.com"},
{id:"NBC",cat:"News",des:"NBC KAMR Texas Amarillo The Latest News and Updates in About Us brought to you by the team at KAMR.",uri:"https://www.myhighplains.com/feed",ext:"https://www.myhighplains.com"},
{id:"NBC",cat:"News",des:"NBC KVEO Texas Brownsville serves the entire surrounding metropolitan area, known as the Rio Grande Valley.",uri:"https://www.kveo.com/feed",ext:"https://www.kveo.com"},
{id:"NBC",cat:"News",des:"NBC KTSM Texas El Paso known as NewsChannel 9, is an NBC affiliated television station based in El Paso, Texas.",uri:"https://www.ktsm.com/feed",ext:"https://www.ktsm.com"},
{id:"CBS",cat:"News",des:"CBS KHOU Texas Houston has been on of the top rated affliates in Texas over two Decades.",uri:"http://rssfeeds.khou.com/khou/local&x=1",ext:"https://www.khou.com/rss"},
{id:"NBC",cat:"News",des:"NBC KPRC Texas Houston breaking news, headlines, weather, and sports.",uri:"https://www.click2houston.com/arcio/rss/tags/local/?size=10",ext:"https://www.click2houston.com"},
{id:"NBC",cat:"News",des:"NBC KETK Texas Jacksonville serving Tyler and Longview, Texas.",uri:"https://www.easttexasmatters.com/feed",ext:"https://www.easttexasmatters.com"},
{id:"ABC",cat:"News",des:"ABC KAMC Texas Lubbock We tell local Lubbock news & weather stories.",uri:"https://www.everythinglubbock.com/feed",ext:"https://www.everythinglubbock.com"},
{id:"ABC",cat:"News",des:"ABC KMID Texas Midland owned and operated by Nexstar Broadcasting Group, which is headquartered in Irving, Texas.",uri:"https://www.yourbasin.com/feed",ext:"https://www.yourbasin.com"},
{id:"NBC",cat:"News",des:"NBC KSAN Texas San Angelo News live streaming online.",uri:"https://www.conchovalleyhomepage.com/feed",ext:"https://www.conchovalleyhomepage.com"},
{id:"CBS",cat:"News",des:"CBS KXII Texas Sherman also serving Ada.",uri:"https://www.kxii.com/content/news/index.rss2",ext:"https://www.kxii.com"},
{id:"NBC",cat:"News",des:"NBC KTAL Texas Texarkana we bring you local news that matters, including Texarkana First News.",uri:"https://www.arklatexhomepage.com/feed",ext:"https://www.arklatexhomepage.com"},
{id:"NBC",cat:"News",des:"NBC KFDX Texas Wichita Falls News and Programming, with weather and traffic.",uri:"https://www.texomashomepage.com/feed",ext:"https://www.texomashomepage.com"},
{id:"ABC",cat:"News",des:"ABC WVNY Vermont Burlington Latest News and Updates in News brought to you by the team at Local 22/44 News.",uri:"https://www.mychamplainvalley.com/feed",ext:"https://www.mychamplainvalley.com"},
{id:"ABC",cat:"News",des:"ABC WVEC Virginia Hampton serving the Hampton Roads area of southeastern Virginia.",uri:"http://rssfeeds.13newsnow.com/wvec/local&x=1",ext:"http://www.13newsnow.com"},
{id:"CBS",cat:"News",des:"CBS WTKR Virginia Norfolk serving the Hampton Roads area of southeastern Virginia.",uri:"https://wtkr.com/feed",ext:"https://wtkr.com"},
{id:"NBC",cat:"News",des:"NBC WAVY Virginia Norfolk serving Chesapeake, Newport News, Hampton, Portsmouth, Virginia Beach, and Suffolk & the rest of Virginia.",uri:"https://www.wavy.com/feed",ext:"https://www.wavy.com"},
{id:"ABC",cat:"News",des:"ABC WRIC Virginia Richmond Petersburg the go-to source for breaking news, local headlines and weather.",uri:"https://www.wric.com/feed",ext:"https://www.wric.com"},
{id:"CBS",cat:"News",des:"CBS WTVR Virginia Richmond News, Weather, and Sports from WTVR Richmond.",uri:"https://wtvr.com/feed",ext:"https://wtvr.com"},
{id:"NBC",cat:"News",des:"NBC WSLS Virginia Roanoke local TV news, Lynchburg, Va., headlines, national news, videos and more.",uri:"https://www.wsls.com/arcio/rss/category/news/?size=10",ext:"https://www.wsls.com"},
{id:"CBS",cat:"News",des:"CBS KREM Washington Spokane serving the Inland Northwest.",uri:"http://rssfeeds.krem.com/krem/headlines/local&x=1",ext:"https://www.krem.com"},
{id:"ABC",cat:"News",des:"ABC WBOY West Virginia Clarksburg local news & weather for north central West Virginia.",uri:"https://www.wboy.com/feed",ext:"https://www.wboy.com"},
{id:"CBS",cat:"News",des:"CBS WOWK West Virginia Huntington we do what we do to make Charleston-Huntington & the rest of West Virginia, Ohio, and Kentucky a better place to live.",uri:"https://www.wowktv.com/feed",ext:"https://www.wowktv.com"},
{id:"ABC",cat:"News",des:"ABC WOAY West Virginia Oak Hill Bluefield late-breaking news, weather, and sports coverage.",uri:"https://woay.tv/feed",ext:"https://woay.tv"},
{id:"CBS",cat:"News",des:"CBS WVNS West Virginia Lewisburg Bluefield serving the Beckley and Oak Hill also covering portions of southwestern Virginia.",uri:"https://www.wvnstv.com/feed",ext:"https://www.wvnstv.com"},
{id:"ABC",cat:"News",des:"ABC WTRF West Virginia Wheeling We tell local Wheeling news & weather stories.",uri:"https://www.wtrf.com/feed",ext:"https://www.wtrf.com"},
{id:"ABC",cat:"News",des:"ABC WYOW Wisconsin Eagle River the station is owned by Quincy Media.",uri:"https://waow.com/feed",ext:"https://waow.com"},
{id:"ABC",cat:"News",des:"ABC WQOW Wisconsin Eau Claire Digging Deeper into issues that affect the Chippewa Valley.",uri:"https://wqow.com/feed",ext:"https://wqow.com"},
{id:"CBS",cat:"News",des:"CBS WFRV Wisconsin Green Bay The Latest News and Updates in News brought to you by the team at WFRV.",uri:"https://www.wearegreenbay.com/feed",ext:"https://www.wearegreenbay.com"},
{id:"ABC",cat:"News",des:"ABC WXOW Wisconsin La Crosse your home for La Crosse area news, weather, and sports.",uri:"https://wxow.com/feed",ext:"https://wxow.com"},
{id:"ABC",cat:"News",des:"ABC WKOW Wisconsin Madison the first TV station in Madison, Wisconsin, established June 30, 1953.",uri:"https://wkow.com/feed",ext:"https://wkow.com"},
{id:"CBS",cat:"News",des:"CBS WDJT Wisconsin Milwaukee your local source for the Milwaukee news, Milwaukee weather, and Milwaukee sports.",uri:"https://www.cbs58.com/rss",ext:"https://www.cbs58.com"},
{id:"CBS",cat:"News",des:"CBS KBJR Wisconsin works in Superior, Duluth, Minnesota, Wisconsin areas.",uri:"https://kbjr6.com/feed",ext:"https://kbjr6.com"},
{id:"ABC",cat:"News",des:"ABC WISN Wisconsin Wausau the day’s biggest stories and ones you may have missed.",uri:"https://www.wisn.com/topstories-rss",ext:"https://www.wisn.com"},
{id:"NBC",cat:"News",des:"NBC15 Wisconsin Southwestern News, Sports, Weather and Live Updates.",uri:"https://www.nbc15.com/content/news/index.rss",ext:"https://www.nbc15.com"},
{id:"Channel News Asia",cat:"World",des:"Channel News Asia is an English language news channel based in Singapore.",uri:"https://www.channelnewsasia.com/rssfeeds/8395986",ext:"https://www.channelnewsasia.com/news/international"},
*/
