var menu=[
{cli:"abcf",ver:"News",sub:"ABC KFSN-TV local Fresno and national news.",api:"https://abc30.com/feed",ext:"https://abc30.com"},
{cli:"ycvc",ver:"News",sub:"KSEE24 CBS47 your central valley in Fresno, California.",api:"https://yourcentralvalley.com/feed",ext:"https://www.yourcentralvalley.com"},
{cli:"abcb",ver:"News",sub:"ABC WCVB Boston news, weather and sports online, anytime.",api:"https://www.wcvb.com/topstories-rss",ext:"https://wcvb.com"},
{cli:"cbsb",ver:"News",sub:"CBS WBZ-TV Boston Local Breaking News From Boston, Mass.",api:"https://boston.cbslocal.com/feed",ext:"https://boston.cbslocal.com/feed"},
{cli:"nbcb",ver:"News",sub:"NBC WBTS-CD Boston local news, national news and Boston breaking news stories.",api:"https://www.nbcboston.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcboston.com"},
{cli:"abcc",ver:"News",sub:"ABC7 Chicago's source for breaking news covering News, Weather, Traffic and Sports.",api:"https://abc7chicago.com/feed",ext:"https://abc7chicago.com"},
{cli:"cbsc",ver:"News",sub:"CBS WBBM-TV Chicago CBS owned-and-operated television station licensed to Chicago, Illinois.",api:"https://chicago.cbslocal.com/feed",ext:"https://chicago.cbslocal.com"},
{cli:"nbcc",ver:"News",sub:"NBC WMAQ-TV Chicago latest weather, traffic, entertainment and political news.",api:"https://www.nbcchicago.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcchicago.com"},
{cli:"cbsf",ver:"News",sub:"CBS KTVT Dallas Fort-Worth Texas breaking news, weather, traffic, and sports.",api:"https://dfw.cbslocal.com/feed",ext:"https://dfw.cbslocal.com"},
{cli:"nbcw",ver:"News",sub:"NBC KXAS-TV Dallas Fort-Worth news, weather, sports, business, lifestyle, traffic and health.",api:"https://www.nbcdfw.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://www.nbcdfw.com"},
{cli:"abch",ver:"News",sub:"ABC KTRK-TV Houston for breaking news from Houston and the surrounding neighborhoods.",api:"https://abc13.com/feed",ext:"https://abc13.com"},
{cli:"ksat",ver:"News",sub:"ABC KSAT-TV San Antonio latest in news, weather and sports.",api:"https://www.ksat.com/arcio/rss/category/news/national/?size=10",ext:"https://www.ksat.com"},
{cli:"abcl",ver:"News",sub:"ABC7 covers Los Angeles news, weather, sports, traffic and live video.",api:"https://abc7.com/feed",ext:"https://abc7.com"},
{cli:"cbsl",ver:"News",sub:"CBS KCBS-TV 7 Los Angeles news, Sports, Weather, Traffic and the Best of LA/OC.",api:"https://losangeles.cbslocal.com/feed",ext:"https://losangeles.cbslocal.com"},
{cli:"nbcl",ver:"News",sub:"NBC KNBC Los Angeles weather, traffic, politics, sports, and entertainment news.",api:"https://www.nbclosangeles.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbclosangeles.com"},
{cli:"abcm",ver:"News",sub:"ABC Local 10 Miami, Florida breaking news and headlines.",api:"https://www.local10.com/feeds/rssFeed/feedServlet?obfType=GMG_RSS_TEASERS&siteId=800006&categoryId=80041&nbRows=10",ext:"https://local10.com"},
{cli:"cbsm",ver:"News",sub:"CBS WFOR-TV Miami a full service television station in Miami and Fort Lauderdale, Florida.",api:"https://miami.cbslocal.com/feed",ext:"https://miami.cbslocal.com"},
{cli:"nbcm",ver:"News",sub:"NBC WTVJ Florida local news, national news and breaking news stories.",api:"https://www.nbcmiami.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcmiami.com"},
{cli:"abc7",ver:"News",sub:"ABC 7 San Francisco local news and headlines.",api:"https://abc7news.com/feed",ext:"https://abc7news.com"},
{cli:"cbso",ver:"News",sub:"CBS KPIX 5 San Francisco News, Sports, Weather, Traffic and the Best of SF.",api:"https://sanfrancisco.cbslocal.com/feed",ext:"https://sanfrancisco.cbslocal.com"},
{cli:"nbco",ver:"News",sub:"NBC KNTV San Franscisco owned-and-operated television station in the Bay Area market.",api:"https://www.nbcbayarea.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcbayarea.com"},
{cli:"abcn",ver:"News",sub:"ABC7 New York covering New York City, New Jersey, and Long Island.",api:"https://abc7ny.com/feed",ext:"https://abc7ny.com"},
{cli:"cbsy",ver:"News",sub:"CBS WCBS-TV New York City 24/7 digital streaming news service. It's always on.",api:"https://newyork.cbslocal.com/feed",ext:"https://newyork.cbslocal.com"},
{cli:"nbcy",ver:"News",sub:"NBC WNBC New York weather, traffic, entertainment and health.",api:"https://www.nbcnewyork.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcnewyork.com"},
{cli:"nbcn",ver:"News",sub:"NBC WRC-TV Washington D.C. news, weather, traffic, entertainment and health.",api:"https://www.nbcwashington.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcwashington.com"},
{cli:"cbsw",ver:"News",sub:"CBS WUSA 9 Washington station licensed to the capital city of Washington, District of Columbia.",api:"http://rssfeeds.wusa9.com/wusa-news&x=1",ext:"https://wusa9.com"},
{cli:"abce",ver:"Style",sub:"ABC Entertainment Latest Celebrity News, Videos & Photos.",api:"https://abcnews.go.com/abcnews/entertainmentheadlines",ext:"https://abcnews.go.com/entertainment"},
{cli:"aolf",ver:"Style",sub:"AOL latest headlines on business, entertainment, politics, world news, tech, sports, and video.",api:"https://www.aol.com/rss",ext:"https://aol.com"},
{cli:"bbce",ver:"Style",sub:"BBC News Entertainment and Arts.",api:"http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",ext:"https://bbc.com/news/entertainment_and_arts"},
{cli:"buzz",ver:"Style",sub:"BuzzFeed  is an American Internet media, news and entertainment company.",api:"https://www.buzzfeed.com/index.xml",ext:"https://www.buzzfeed.com"},
{cli:"soon",ver:"Style",sub:"ComingSoon.net has New Movies, Movie Trailers, TV, Digital, Blu-ray & Video Game News!",api:"https://www.comingsoon.net/feed",ext:"https://comingsoon.net"},
{cli:"cbse",ver:"Style",sub:"CBS Entertainment Latest celebrity news, movies, TV shows, and more.",api:"https://www.cbsnews.com/latest/rss/entertainment",ext:"https://cbsnews.com/latest/rss/entertainment"},
{cli:"rcel",ver:"Style",sub:"Celebrity Hub subreddit Pictures and GIFs of actresses, singers, models, athletes and celebs.",api:"https://www.reddit.com/r/celebhub/.rss",ext:"https://reddit.com/r/celebhub"},
{cli:"cnne",ver:"Style",sub:"CNN Entertainment News Celebrities, Movies, TV, and Music.",api:"http://rss.cnn.com/rss/cnn_showbiz.rss",ext:"https://cnn.com/entertainment"},
{cli:"dead",ver:"Style",sub:"Deadline is the first to break up-to-the-minute entertainment, Hollywood and media news.",api:"https://deadline.com/feed",ext:"https://deadline.com"},
{cli:"dgtm",ver:"Style",sub:"Digital Trends Movie reviews, TV Show recaps, previews, and news.",api:"https://www.digitaltrends.com/movies/feed/",ext:"https://digitaltrends.com/movies"},
{cli:"dlbs",ver:"Style",sub:"Daily Beast is a news and opinion website focusing on politics, power and Entertainment culture.",api:"https://feeds.thedailybeast.com/summary/rss/articles",ext:"https://www.thedailybeast.com"},
{cli:"rent",ver:"Style",sub:"Entertainment subreddit has news and discussion of the entertainment industry.",api:"https://www.reddit.com/r/entertainment/.rss",ext:"https://reddit.com/r/entertainment"},
{cli:"esqf",ver:"Style",sub:"Esquire is your destination for the latest Entertainment news headlines.",api:"https://www.esquire.com/rss/entertainment.xml",ext:"https://esquire.com"},
{cli:"gent",ver:"Style",sub:"Google Entertainment headlines, opinions, and news.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=film+movie+music+art+entertainment&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{cli:"indw",ver:"Style",sub:"IndieWire has grown over decades as a preeminent source for film and television news.",api:"https://www.indiewire.com/feed",ext:"https://www.indiewire.com"},
{cli:"invs",ver:"Style",sub:"Inverse covers the latest news on science, innovation, entertainment, technology and culture.",api:"https://www.inverse.com/feed/articles/1.rss",ext:"https://www.inverse.com"},
{cli:"jsjd",ver:"Style",sub:"Just Jared Jr. is the definitive site for celebrity news.",api:"http://www.justjared.com/feed",ext:"http://justjared.com"},
{cli:"rmov",ver:"Style",sub:"Movies subreddit News & Discussion about Major Motion Pictures.",api:"https://www.reddit.com/r/movies/.rss",ext:"https://reddit.com/r/movies"},
{cli:"meta",ver:"Style",sub:"Metacritic aggregates reviews of films, TV shows, music albums, and video games.",api:"https://www.metacritic.com/rss/features",ext:"https://www.metacritic.com"},
{cli:"movw",ver:"Style",sub:"Movieweb is the fastest, most complete movie & tv coverage on the planet.",api:"https://movieweb.com/rss/all-news",ext:"https://movieweb.com"},
{cli:"pepl",ver:"Style",sub:"People is an American weekly magazine of celebrity and human-interest stories.",api:"https://people.com/tag/news/feed",ext:"https://people.com"},
{cli:"pzhl",ver:"Style",sub:"PerezHilton is known for posts covering gossip items about celebrities.",api:"https://perezhilton.com/feed",ext:"https://perezhilton.com"},
{cli:"rost",ver:"Style",sub:"RollingStone Magazine, the authority on music, entertainment, politics and Entertainment culture.",api:"https://www.rollingstone.com/feed",ext:"https://rollingstone.com"},
{cli:"snop",ver:"Style",sub:"Snopes.com’s fact checking and original investigative reporting.",api:"https://www.snopes.com/feed",ext:"https://www.snopes.com"},
{cli:"nyet",ver:"Style",sub:"NYPost Entertainment latest and breaking news on celebrities, movies, and TV shows.",api:"https://nypost.com/entertainment/feed",ext:"https://nypost.com/entertainment/feed"}, 
{cli:"tmzn",ver:"Style",sub:"TMZ is a tabloid news website that was a collaboration between AOL and Telepictures Productions.",api:"https://www.tmz.com/rss.xml",ext:"https://tmz.com"},
{cli:"uprx",ver:"Style",sub:"Uproxx is an entertainment and Entertainmentular culture news website.",api:"http://feeds.feedburner.com/uproxx/features",ext:"https://uproxx.com"},
{cli:"vanf",ver:"Style",sub:"Vanity Fair is a magazine of Entertainmentular culture, fashion, and current affairs.",api:"https://www.vanityfair.com/feed/rss",ext:"https://vanityfair.com"},
{cli:"rvid",ver:"Style",sub:"Video subreddit The best place for video content of all kinds.",api:"https://www.reddit.com/r/videos/.rss",ext:"https://reddit.com/r/videos"},
{cli:"wase",ver:"Style",sub:"Washington Times Showbiz News and Entertainment News.",api:"https://www.washingtontimes.com/rss/headlines/culture/entertainment",ext:"https://washingtontimes.com/culture/entertainment"},
{cli:"yahe",ver:"Style",sub:"Yahoo Entertainment News, Celebrity, Movie, TV.",api:"https://www.yahoo.com/entertainment/rss",ext:"https://yahoo.com/entertainment"},
{cli:"yahc",ver:"Style",sub:"Yahoo Celebrity for the latest news and gossip on the world's celebrities.",api:"https://www.yahoo.com/celebrity/rss",ext:"https://yahoo.com/celebrity"},
{cli:"rapp",ver:"Social",sub:"Apple subreddit  to discuss Apple devices and software, including news, rumors, opinions and analysis.",api:"https://www.reddit.com/r/apple/.rss",ext:"https://www.reddit.com/r/apple"},
{cli:"rand",ver:"Social",sub:"Android subreddit news, reviews, tips, and discussions about rooting, tutorials, and apps.",api:"https://www.reddit.com/r/android/.rss",ext:"https://reddit.com/r/android"},
{cli:"rnew",ver:"Social",sub:"News subreddit news articles news relating to the United States and the rest of the World.",api:"https://www.reddit.com/r/news/.rss",ext:"https://reddit.com/r/news"},
{cli:"arch",ver:"Social",sub:"Arch Linux BBS is a Linux distribution for computers based on x86-64 architectures.",api:"https://bbs.archlinux.org/extern.php?type=rss",ext:"http://bbs.archlinux.org"},
{cli:"rarc",ver:"Social",sub:"Arch Linux subreddit discusses topics revolving around Arch Linux.",api:"https://www.reddit.com/r/archlinux/.rss",ext:"https://reddit.com/r/archlinux"},
{cli:"rbsd",ver:"Social",sub:"BSD subreddit about Berkeley Software Distribution an operating system based on Unix.",api:"https://www.reddit.com/r/bsd/.rss",ext:"https://reddit.com/r/bsd"},
{cli:"rcmd",ver:"Social",sub:"Commandline subreddit with questions and answers.",api:"https://www.reddit.com/r/commandline/.rss",ext:"https://reddit.com/r/commandline"},
{cli:"rcom",ver:"Social",sub:"Computer subreddit with questions and opinions.",api:"https://www.reddit.com/r/computers/.rss",ext:"https://reddit.com/r/computers"},
{cli:"rdeb",ver:"Social",sub:"Debian Linux subreddit covers topics revolving around Debian OS.",api:"https://www.reddit.com/r/debian/.rss",ext:"https://reddit.com/r/debian"},
{cli:"rdev",ver:"Social",sub:"Devops subreddit with 117,000 members created in 2010.",api:"https://www.reddit.com/r/devops/.rss",ext:"https://reddit.com/r/devops"},
{cli:"4diy",ver:"Social",sub:"DIY board discusses projects, ask questions, covers topics, exchanges ideas and techniques.",api:"http://boards.4channel.org/diy/index.rss",ext:"http://boards.4channel.org/diy"},
{cli:"rfed",ver:"Social",sub:"Fedora subreddit community for users, developers and people interested in Fedora.",api:"https://www.reddit.com/r/fedora/.rss",ext:"https://reddit.com/r/fedora"},
{cli:"4gch",ver:"Social",sub:"G Technology is a board that discusses technology.",api:"http://boards.4chan.org/g/index.rss",ext:"http://boards.4channel.org/g/"},
{cli:"rgms",ver:"Social",sub:"Games subreddit aims to provide a place for informative and interesting gaming content.",api:"http://www.reddit.com/r/games/.rss",ext:"https://reddit.com/r/games"},
{cli:"glin",ver:"Social",sub:"Google Linux combination of top resources for linux.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=linux&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{cli:"gsoc",ver:"Social",sub:"Google Social news from top social media platforms.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=social+facebook+twitter+instagram+tiktok+snapchat+news&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{cli:"hack",ver:"Social",sub:"Hacker News is a reader ran headline submission news purveyor.",api:"https://news.ycombinator.com/rss",ext:"https://news.ycombinator.com"},
{cli:"rhck",ver:"Social",sub:"Hacking subreddit dedicated to hacking and hackers.",api:"https://www.reddit.com/r/hacking/.rss",ext:"https://reddit.com/r/hacking"},
{cli:"rios",ver:"Social",sub:"iOS subreddit for everything Apple iOS.",api:"https://www.reddit.com/r/ios/.rss",ext:"https://www.reddit.com/r/ios"},
{cli:"rjsc",ver:"Social",sub:"Javascript subreddit All about the JavaScript programming language!",api:"https://www.reddit.com/r/javascript/.rss",ext:"https://www.reddit.com/r/javascript"},
{cli:"rlnx",ver:"Social",sub:"Linux subreddit discusses topics evolving around Linux.",api:"https://www.reddit.com/r/linux/.rss",ext:"https://reddit.com/r/linux"},
{cli:"rnod",ver:"Social",sub:"Node subreddit all about NodeJs, created in 2009 with 141,000 members.",api:"https://www.reddit.com/r/node/.rss",ext:"https://www.reddit.com/r/node"},
{cli:"rpro",ver:"Social",sub:"Programming subreddit shares user submitted articles on programming.",api:"https://www.reddit.com/r/programming/.rss",ext:"https://reddit.com/r/programming"},
{cli:"rpyt",ver:"Social",sub:"Python subreddit about the dynamic, interpreted, interactive, object-oriented, extensible language Python.",api:"https://www.reddit.com/r/python/.rss",ext:"https://reddit.com/r/python"},
{cli:"rred",ver:"Social",sub:"Redhat subreddit discussion for Red Hat and Red Hat technologies!",api:"https://reddit.com/r/redhat/.rss",ext:"https://reddit.com/r/redhat"},
{cli:"rsec",ver:"Social",sub:"Security subreddit has been around for 11 years and has 93k subscribers.",api:"https://www.reddit.com/r/security/.rss",ext:"https://reddit.com/r/security"}, 
{cli:"sdot",ver:"Social",sub:"Slashdot is a social news website that originally billed itself as News for Nerds.",api:"http://rss.slashdot.org/Slashdot/slashdot",ext:"https://slashdot.org"},
{cli:"sope",ver:"Social",sub:"Softpedia Linux is a software and tech-news website based in Romania.",api:"https://linux.softpedia.com/backend.xml",ext:"https://linux.softpedia.com"},
{cli:"rsys",ver:"Social",sub:"Sysadmin subreddit dedicated to the profession of Computer System Administration.",api:"https://www.reddit.com/r/sysadmin/.rss",ext:"https://reddit.com/r/sysadmin"},
{cli:"rtch",ver:"Social",sub:"Tech subreddit the intelligent discussion of innovations and changes to technology.",api:"https://www.reddit.com/r/tech/.rss",ext:"https://www.reddit.com/r/tech"},
{cli:"rtec",ver:"Social",sub:"Technology subreddit users opinions and submitted articles.",api:"https://www.reddit.com/r/technology/.rss",ext:"https://reddit.com/r/technology"},
{cli:"rstm",ver:"Social",sub:"Steam subreddit for members of the Steam Community.",api:"https://www.reddit.com/r/steam/.rss",ext:"https://reddit.com/r/steam"},
{cli:"rcar",ver:"Social",sub:"Ubuntu subreddit or news, information and general discussion related to Ubuntu..",api:"https://www.reddit.com/r/ubuntu/.rss",ext:"https://reddit.com/r/ubuntu"},
{cli:"ruxp",ver:"Social",sub:"Unix subreddit *NIX desktops, themes, and nifty configurations",api:"https://www.reddit.com/r/unixporn/.rss",ext:"https://reddit.com/r/unixporn"},
{cli:"rwlp",ver:"Social",sub:"Wallpaper subreddit computer desktops and background images.",api:"https://www.reddit.com/r/wallpaper/.rss",ext:"https://reddit.com/r/wallpaper"},
{cli:"rwps",ver:"Social",sub:"Wallpapers subreddit Work-safe wallpapers from all over!",api:"https://www.reddit.com/r/wallpapers/.rss",ext:"https://reddit.com/r/wallpapers"},
{cli:"4cwg",ver:"Social",sub:"Wallpapers General including Desktops, Builds, Mobile, Image mods, NO Requests.",api:"http://boards.4chan.org/wg/index.rss",ext:"http://boards.4chan.org/wg"},
{cli:"rwin",ver:"Social",sub:"Windows subreddit about the operating system released by Microsoft as part of the Windows NT family.",api:"https://www.reddit.com/r/windows/.rss",ext:"https://www.reddit.com/r/windows"},
{cli:"abcs",ver:"Sports",sub:"ABC Sports the latest sports news and articles and more.",api:"https://abcnews.go.com/abcnews/sportsheadlines",ext:"https://abcnews.go.com/Sports"},
{cli:"rbas",ver:"Sports",sub:"Baseball subreddit for the bat-and-ball sport played between two teams of nine players.",api:"https://www.reddit.com/r/baseball/.rss",ext:"https://reddit.com/r/baseball"},
{cli:"bbcs",ver:"Sports",sub:"BBC Sports News from around the world.",api:"http://feeds.bbci.co.uk/sport/rss.xml",ext:"https://bbc.com/sport"},
{cli:"bjpn",ver:"Sports",sub:"BJPENN has become one of the most reliable destinations for your MMA and UFC needs. ",api:"https://www.bjpenn.com/feed",ext:"https://bjpenn.com"},
{cli:"blrp",ver:"Sports",sub:"Bleacher Report is a website that focuses on sport and sports culture.",api:"https://bleacherreport.com/articles/feed",ext:"https://bleacherreport.com"},
{cli:"cbss",ver:"Sports",sub:"CBS Sports is an American sports news website operated by CBS Interactive.",api:"https://rss.cbssports.com/rss/headlines",ext:"https://cbssports.com"},
{cli:"rcfb",ver:"Sports",sub:"CFB subreddit forum for all things college football focused on NCAA football.",api:"https://www.reddit.com/r/cfb/.rss",ext:"https://reddit.com/r/cfb"},
{cli:"cnns",ver:"Sports",sub:"CNN Sports catalogues the latest news from around the world.",api:"http://rss.cnn.com/rss/edition_sport.rss",ext:"https://cnn.com/sport"},
{cli:"deds",ver:"Sports",sub:"Deadspin brings you the latest sports news, stories, videos, and more.",api:"https://deadspin.com/rss",ext:"https://deadspin.com"},
{cli:"dgtc",ver:"Sports",sub:"Digital Trends world of cars, speed and power.",api:"https://www.digitaltrends.com/cars/feed",ext:"https://digitaltrends.com/cars"},
{cli:"espn",ver:"Sports",sub:"ESPN is a cable network that plays live and taped sporting events.",api:"https://www.espn.com/espn/rss/news",ext:"https://espn.com"},
{cli:"enfl",ver:"Sports",sub:"ESPN NFL football news, scores, stats, standings, fantasy games, and more.",api:"http://www.espn.com/espn/rss/nfl/news",ext:"https://espn.com/nfl"},
{cli:"enba",ver:"Sports",sub:"ESPN NBA team stats, schedules, rosters, depth charts and more.",api:"http://www.espn.com/espn/rss/nba/news",ext:"https://espn.com/nba"},
{cli:"emlb",ver:"Sports",sub:"ESPN MLB baseball news, scores, stats, standings, fantasy games, and more.",api:"http://www.espn.com/espn/rss/mlb/news",ext:"https://espn.com/mlb"},
{cli:"enhl",ver:"Sports",sub:"ESPN NHL hockey news, scores, stats, standings, fantasy games, and more.",api:"http://www.espn.com/espn/rss/nhl/news",ext:"https://espn.com/nhl"},
{cli:"ecfb",ver:"Sports",sub:"ESPN CFB National Collegiate Athletic Association Division I Football Bowl Subdivision.",api:"http://www.espn.com/espn/rss/ncf/news",ext:"https://espn.com/ncf"},
{cli:"rfoo",ver:"Sports",sub:"Football subreddit discusses and headlines topic around football.",api:"https://www.reddit.com/r/football/.rss",ext:"https://reddit.com/r/football"},
{cli:"foxs",ver:"Sports",sub:"Fox Sports is a wide array of multi-platform US-based sports assets.",api:"https://api.foxsports.com/v1/rss?partnerKey=zBaFxRyGKCfxBagJG9b8pqLyndmvo7UU",ext:"https://foxsports.com"},
{cli:"goal",ver:"Sports",sub:"Goal.com latest soccer news, live scores, results, rumours, and transfers.",api:"https://www.goal.com/feeds/en/news",ext:"https://goal.com"},
{cli:"gspo",ver:"Sports",sub:"Google Sports NBA, MLB, MMA, NFL, NHL, NCAA.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=sports+nba+nfl+ncaa+nhl+mlb+mma+cfb&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{cli:"rhoc",ver:"Sports",sub:"Hockey subreddit NHL, AHL, KHL, NWHL, IIHF and every other hockey league.",api:"https://www.reddit.com/r/hockey/.rss",ext:"https://reddit.com/r/hockey"},
{cli:"jalp",ver:"Sports",sub:"Jalopnik is a news site about cars, racing, transportation, airplanes, and motorcycles",api:"https://jalopnik.com/rss",ext:"https://jalopnik.com"},
{cli:"rmlb",ver:"Sports",sub:"MLB subreddit covers Major League Baseball headlines and news.",api:"https://www.reddit.com/r/mlb/.rss",ext:"https://reddit.com/r/mlb"},
{cli:"mlbn",ver:"Sports",sub:"MLB.com is the official site of Major League Baseball.",api:"https://www.mlb.com/feeds/news/rss.xml",ext:"https://mlb.com"},
{cli:"mmaj",ver:"Sports",sub:"MMAJunkie Radio is a weekly Internet radio show broadcast from Las Vegas, Nevada.",api:"https://mmajunkie.com/news/feed",ext:"https://mmajunkie.com"},
{cli:"mman",ver:"Sports",sub:"MMA.news offers coverage of the MMA world with original content.",api:"https://www.mmanews.com/feed",ext:"https://mmanews.com"},
{cli:"rmma",ver:"Sports",sub:"MMA subreddit for all things Mixed Martial Arts.",api:"https://www.reddit.com/r/MMA/.rss",ext:"https://reddit.com/r/MMA"},
{cli:"nbcs",ver:"Sports",sub:"NBC Sports is responsible for the televising of many sports events.",api:"https://sports.nbcsports.com/feed",ext:"https://nbcsports.com"},
{cli:"rnfl",ver:"Sports",sub:"NFL subreddit covers National Football League News & Discussion.",api:"https://www.reddit.com/r/nfl/.rss",ext:"https://reddit.com/r/nfl"},
{cli:"nysp",ver:"Sports",sub:"NYPost Sports including scores, trade rumors and standings for baseball, football, and basketball.",api:"https://nypost.com/sports/feed",ext:"https://nypost.com/sports"},
{cli:"ncaa",ver:"Sports",sub:"NCAA FBS College Football headlines.",api:"https://www.ncaa.com/news/football/fbs/rss.xml",ext:"https://ncaa.com/sports/football/fbs"},
{cli:"rtsp",ver:"Sports",sub:"RT Sport delivers latest news on sports from around the world.",api:"https://www.rt.com/rss/sport",ext:"https://rt.com/sport"},
{cli:"sprt",ver:"Sports",sub:"Sports Illustrated Top Stories is a weekly sports magazine that originated in 1954.",api:"https://www.si.com/rss/si_topstories.rss",ext:"https://si.com"},
{cli:"sfan",ver:"Sports",sub:"Sports Illustrated Fantasy drafts, mockups, trades, rumors, deadlines.",api:"https://www.si.com/rss/si_fantasy.rss",ext:"https://www.si.com/fantasy"},
{cli:"smlb",ver:"Sports",sub:"Sports Illustrated MLB news, scores, stats, and fantasy.",api:"https://www.si.com/rss/si_mlb.rss",ext:"https://www.si.com/mlb"},
{cli:"smma",ver:"Sports",sub:"Sports Illustrated MMA fight previews, fighter face offs, and opinion.",api:"https://www.si.com/rss/si_mma.rss",ext:"https://www.si.com/mma"},
{cli:"snba",ver:"Sports",sub:"Sports Illustrated NBA headlines and analysis.",api:"https://www.si.com/rss/si_nba.rss",ext:"https://www.si.com/nba"},
{cli:"scfb",ver:"Sports",sub:"Sports Illustrated NCAA College Football headlines and stories.",api:"https://www.si.com/rss/si_ncaaf.rss",ext:"https://www.si.com/college/college-football"},
{cli:"snfl",ver:"Sports",sub:"Sports Illustrated NFL latest news, scores, schedules, fantasy analysis.",api:"https://www.si.com/rss/si_nfl.rss",ext:"https://www.si.com/nfl"},
{cli:"sfut",ver:"Sports",sub:"Sports Illustrated Soccer stories, news, headlines, and analysis.",api:"https://www.si.com/rss/si_soccer.rss",ext:"https://www.si.com/soccer"},
{cli:"sten",ver:"Sports",sub:"Sports Illustrated Tennis matches, tournaments, previews, and news.",api:"https://www.si.com/rss/si_tennis.rss",ext:"https://www.si.com/tennis"},
{cli:"4chn",ver:"Sports",sub:"Sports is a board that discusses International Sports.",api:"http://boards.4chan.org/sp/index.rss",ext:"http://boards.4channel.org/sp/"},
{cli:"spnw",ver:"Sports",sub:"Sporting News, originally The Sporting News, was established in 1886 as a weekly U.S. magazine.",api:"http://www.sportingnews.com/us/rss",ext:"http://sportingnews.com"},
{cli:"rspo",ver:"Sports",sub:"Sports subreddit for all the latest headlines and discussion in sports.",api:"https://www.reddit.com/r/sports/.rss",ext:"https://reddit.com/r/sports"},
{cli:"rten",ver:"Sports",sub:"Tennis subreddit discusses tennis, from tour professionals to recreational players.",api:"https://www.reddit.com/r/tennis/.rss",ext:"https://reddit.com/r/tennis"},
{cli:"scor",ver:"Sports",sub:"The Score NFL is the ultimate, personalized mobile sports experience.",api:"https://feeds.thescore.com/nfl.rss",ext:"https://thescore.com/nfl/news"},
{cli:"scrm",ver:"Sports",sub:"The Score MLB is the ultimate, personalized mobile sports experience.",api:"https://feeds.thescore.com/mlb.rss",ext:"https://thescore.com/mlb/news"},
{cli:"scrb",ver:"Sports",sub:"The Score MMA is the ultimate, personalized mobile sports experience.",api:"https://feeds.thescore.com/mma.rss",ext:"https://thescore.com/mma/news"},
{cli:"mmau",ver:"Sports",sub:"The Underground is a MMA website that features daily MMA news.",api:"http://www.mixedmartialarts.com/news/feed",ext:"http://mixedmartialarts.com"},
{cli:"tieb",ver:"Sports",sub:"Tiebreaker sports news headlines from around the world.",api:"https://www.tiebreaker.com/feed",ext:"https://www.tiebreaker.com"},
{cli:"ufcn",ver:"Sports",sub:"UFC is an American mixed martial arts promotion company based in Las Vegas, Nevada.",api:"https://www.ufc.com/rss/news",ext:"https://ufc.com"},
{cli:"vcfl",ver:"Sports",sub:"Vice Fightland is a website covering mixed martial arts (MMA).",api:"http://fightland.vice.com/rss",ext:"http://fightland.vice.com"},
{cli:"yahs",ver:"Sports",sub:"Yahoo! Sports has Comprehensive  news, scores, standings, fantasy games, rumors, and more.",api:"https://sports.yahoo.com/rss",ext:"https://sports.yahoo.com"},
{cli:"abct",ver:"Technology",sub:"ABC Technology for latest science news, technology news, and more.",api:"https://abcnews.go.com/abcnews/technologyheadlines",ext:"https://abcnews.go.com/technology"},
{cli:"amsg",ver:"Technology",sub:"AMS founded in 1888 to further the interests of mathematical research and scholarship.",api:"http://www.ams.org/cgi-bin/content/news_items.cgi?rss=1",ext:"http://www.ams.org"},
{cli:"nica",ver:"Technology",sub:"Ars Technica has became a trusted source for technology news.",api:"http://feeds.arstechnica.com/arstechnica/index?format=xml",ext:"https://arstechnica.com"},
{cli:"bbcn",ver:"Technology",sub:"BBC Technology news, articles, and more.",api:"http://feeds.bbci.co.uk/news/technology/rss.xml",ext:"https://bbc.co.uk/news/technology"},
{cli:"beta",ver:"Technology",sub:"BetaNews is a leading source of technology news and analysis.",api:"http://feeds.betanews.com/bn",ext:"https://betanews.com"},
{cli:"bgrt",ver:"Technology",sub:"BGR is a destination for news focused on consumer electronics markets.",api:"https://bgr.com/tech/feed",ext:"https://bgr.com/tech"},
{cli:"insi",ver:"Technology",sub:"Business Insider is a growing business site with financial, media, and tech.",api:"https://www.businessinsider.com/rss",ext:"https://businessinsider.com"},
{cli:"cbst",ver:"Technology",sub:"CBS Technology on social media, artificial intelligence, computers and more.",api:"https://www.cbsnews.com/latest/rss/technology",ext:"https://cbsnews.com/technology"},
{cli:"cnbc",ver:"Technology",sub:"CNBC is an American television news channel that is owned by NBCUniversal.",api:"https://www.cnbc.com/id/19854910/device/rss/rss.html",ext:"https://cnbc.com/technology"},
{cli:"cnet",ver:"Technology",sub:"CNET is an American media website that publishes reviews, news, articles, and videos on technology.",api:"https://www.cnet.com/rss/news",ext:"https://cnet.com"},
{cli:"comp",ver:"Technology",sub:"Computer Weekly stands out from the many technology news websites.",api:"https://www.computerweekly.com/rss/RSS-Feed.xml",ext:"https://computerweekly.com"},
{cli:"dgtr",ver:"Technology",sub:"Digital Trends is a technology news, lifestyle, and information website.",api:"https://www.digitaltrends.com/feed",ext:"https://digitaltrends.com"},
{cli:"engt",ver:"Technology",sub:"Engadget is a technology blog network with daily coverage of gadgets and consumer electronics.",api:"https://www.engadget.com/rss.xml",ext:"https://engadget.com"},
{cli:"forb",ver:"Technology",sub:"Forbes is a global media company, focusing on business, investing, and technology.",api:"https://www.forbes.com/most-popular/feed",ext:"https://forbes.com"},
{cli:"gmln",ver:"Technology",sub:"GamingonLinux Latest articles and Games.",api:"https://www.gamingonlinux.com/article_rss.php",ext:"https://gamingonlinux.com"},
{cli:"geek",ver:"Technology",sub:"GeekWire is an American technology news site that covers startups and established technology companies.",api:"https://www.geekwire.com/feed",ext:"https://geekwire.com"},
{cli:"gizm",ver:"Technology",sub:"Gizmodo is a design, technology, science and science fiction website.",api:"https://gizmodo.com/rss",ext:"https://gizmodo.com"},
{cli:"ghck",ver:"Technology",sub:"gHacks the independent technology news blog.",api:"https://www.ghacks.net/feed",ext:"https://ghacks.net"},
{cli:"gtec",ver:"Technology",sub:"Google Technology news, opinion, and analysis.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=technology&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{cli:"haad",ver:"Technology",sub:"Hackaday serves up Fresh Hacks Every Day from around the Internet.",api:"https://hackaday.com/feed",ext:"https://hackaday.com"},
{cli:"indp",ver:"Technology",sub:"Independent.co.uk for Latest Gadgets and Tech news.",api:"http://www.independent.co.uk/life-style/gadgets-and-tech/rss",ext:"https://independent.co.uk/life-style/gadgets-and-tech"},
{cli:"info",ver:"Technology",sub:"InfoWorld is an information technology media business.",api:"https://www.infoworld.com/index.rss",ext:"https://infoworld.com"}, 
{cli:"kota",ver:"Technology",sub:"Kotaku is a news and opinion site about games and things serious gamers care about.",api:"https://kotaku.com/rss",ext:"https://kotaku.com"},
{cli:"kreb",ver:"Technology",sub:"Krebs on categoryurity covering computer categoryurity and cybercrime.",api:"http://feeds.feedburner.com/KrebsOncategoryurity",ext:"https://krebsoncategoryurity.com"},
{cli:"ltms",ver:"Technology",sub:"Los Angeles Times tech is a daily newspaper that is published in Los Angeles, California.",api:"https://www.latimes.com/business/technology/rss2.0.xml",ext:"https://latimes.com/business/technology"},
{cli:"lifh",ver:"Technology",sub:"Lifehacker is the ultimate authority on optimizing every aspect of your life. Do everything better.",api:"https://lifehacker.com/rss",ext:"https://lifehacker.com"},
{cli:"llup",ver:"Technology",sub:"Leak-Lookup latest database leaks and records counting.",api:"https://leak-lookup.com/rss",ext:"https://leak-lookup.com"},
{cli:"lxcm",ver:"Technology",sub:"Linux.com News For Open Source Professionals.",api:"https://www.linux.com/feed",ext:"https://linux.com"},
{cli:"betp",ver:"Technology",sub:"Medium's advice for programmers covering tutorials, leadership, management, and productivity.",api:"https://medium.com/feed/better-programming",ext:"https://medium.com/better-programming"},
{cli:"mirt",ver:"Technology",sub:"Mirror.co.uk Technology best stories, opinion, pictures and video.",api:"https://www.mirror.co.uk/tech/?service=rss",ext:"https://mirror.co.uk/tech"},
{cli:"umit",ver:"Technology",sub:"MIT is a top university, in science and engineering, cognitive science, philosophy and linguistics.",api:"http://news.mit.edu/rss/feed",ext:"http://news.mit.edu"},
{cli:"mitr",ver:"Technology",sub:"MIT Technology Review is to bring about better-informed and more conscious decisions about technology.",api:"https://www.technologyreview.com/topnews.rss",ext:"https://technologyreview.com"},
{cli:"nasa",ver:"Technology",sub:"NASA.gov brings you the latest images, videos and news from America's space agency.",api:"https://www.nasa.gov/rss/dyn/breaking_news.rss",ext:"https://nasa.gov"},
{cli:"nbct",ver:"Technology",sub:"NBC News Tech for latest news on technology businesses and Internet media.",api:"http://feeds.nbcnews.com/nbcnews/public/tech",ext:"https://nbcnews.com/tech-media"},
{cli:"nypo",ver:"Technology",sub:"New York Post technology, established Nov 16, 1801, describes itself as the nation's oldest daily newspaper.",api:"https://nypost.com/tech/feed",ext:"https://nypost.com/tech"},
{cli:"nytm",ver:"Technology",sub:"New York Times is a newspaper based in New York City with worldwide influence.",api:"https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",ext:"https://nytimes.com/categorytion/technology"},
{cli:"pack",ver:"Technology",sub:"Packet Storm is a information categoryurity website offering current and historical computer categoryurity tools.",api:"https://rss.packetstormcategoryurity.com/news/tags/usa",ext:"https://packetstormcategoryurity.com"},
{cli:"pcwd",ver:"Technology",sub:"PC World is one of the United Kingdom's largest retail chains of mass market computer megastores.",api:"https://www.pcworld.com/index.rss",ext:"https://pcworld.com"},
{cli:"phor",ver:"Technology",sub:"Phoronix Linux Hardware Reviews & News.",api:"https://www.phoronix.com/rss.php",ext:"https://phoronix.com"},
{cli:"phys",ver:"Technology",sub:"Phys.org has latest news on science in Physics, Space Science, Earth Science, Health and Medicine.",api:"https://phys.org/rss-feed",ext:"https://phys.org"},
{cli:"tico",ver:"Technology",sub:"Politico Tech strives to be the dominant source for politics and policy.",api:"https://www.politico.com/rss/morningtech.xml",ext:"https://politico.com"},
{cli:"mech",ver:"Technology",sub:"Popular Mechanics is a magazine of popular science and technology.",api:"https://www.popularmechanics.com/rss/all.xml",ext:"https://popularmechanics.com"},
{cli:"rdwr",ver:"Technology",sub:"ReadWrite was founded on April 20, 2003, by Richard MacManus, as ReadWriteWeb.",api:"https://readwrite.com/feed",ext:"https://readwrite.com"},
{cli:"rctn",ver:"Technology",sub:"Reclaim The Net - Restoring individual liberty online. Free speech. Privacy",api:"https://reclaimthenet.org/feed",ext:"https://reclaimthenet.org"},
{cli:"scdl",ver:"Technology",sub:"ScienceDaily Top Technology News.",api:"https://www.sciencedaily.com/rss/top/technology.xml",ext:"https://sciencedaily.com/news/top/technology"},
{cli:"skyn",ver:"Technology",sub:"Sky News technology is a British news organisation, which operates a TV network.",api:"http://feeds.skynews.com/feeds/rss/technology.xml",ext:"https://sky.com/technology"},
{cli:"crch",ver:"Technology",sub:"TechCrunch reports on the business of technology, startups, venture capital funding, and Silicon Valley.",api:"http://feeds.feedburner.com/TechCrunch",ext:"https://techcrunch.com"},
{cli:"meme",ver:"Technology",sub:"TechMeme is an automated news curation service focused on the leading edge of technology.",api:"https://www.techmeme.com/feed.xml",ext:"https://techmeme.com"},
{cli:"tecr",ver:"Technology",sub:"TechRadar is an online publication focused on technology.",api:"https://www.techradar.com/rss",ext:"https://techradar.com"},
{cli:"repu",ver:"Technology",sub:"TechRepublic is an online trade publication and social community for IT professionals.",api:"https://www.techrepublic.com/rssfeeds/articles",ext:"https://techrepublic.com"},
{cli:"tpun",ver:"Technology",sub:"TechPowerUp is a leading technology publication, on the forefront of PC technologies.",api:"https://www.techpowerup.com/rss/news",ext:"https://techpowerup.com"},
{cli:"spot",ver:"Technology",sub:"TechSpot is a leading computer and technology publication established in 1998.",api:"https://www.techspot.com/backend.xml",ext:"https://techspot.com"},
{cli:"regi",ver:"Technology",sub:"TheRegister.co.uk is a British technology news and opinion website co-founded in 1994.",api:"https://www.theregister.co.uk/headlines.atom",ext:"https://theregister.co.uk"},
{cli:"usat",ver:"Technology",sub:"USA Today Technology is an internationally distributed American daily, middle-market newspaper.",api:"http://rssfeeds.usatoday.com/usatoday-techtopstories&x=1",ext:"https://usatoday.com/tech/"},
{cli:"wall",ver:"Technology",sub:"Wall Street Journals latest tech news, reviews, and stories.",api:"https://feeds.a.dj.com/rss/RSSWSJD.xml",ext:"https://wsj.com/news/technology"},
{cli:"wasp",ver:"Technology",sub:"Washington Post is a major American daily newspaper published in Washington, D.C.",api:"http://feeds.washingtonpost.com/rss/business/technology",ext:"https://washingtonpost.com/business/technology"},
{cli:"wast",ver:"Technology",sub:"Washington Times is an American daily newspaper published in Washington, D.C.",api:"https://www.washingtontimes.com/rss/headlines/culture/technology",ext:"https://washingtontimes.com/culture/technology"},
{cli:"wccf",ver:"Technology",sub:"Wccftech has the latest updates in the world of Tech, Mobile, PC Hardware, Gaming & Finance.",api:"https://wccftech.com/feed",ext:"https://wccftech.com"},
{cli:"wire",ver:"Technology",sub:"WIRED is where tomorrow is realized. It is the essential source of information.",api:"https://www.wired.com/feed/rss",ext:"https://wired.com"},
{cli:"yaho",ver:"Technology",sub:"Yahoo is a web services provider headquartered in California, and owned by Verizon Media.",api:"https://www.yahoo.com/tech/rss",ext:"https://finance.yahoo.com/tech"},
{cli:"zdnt",ver:"Technology",sub:"ZDNet is a business technology news website published by CBS Interactive.",api:"https://www.zdnet.com/news/rss.xml",ext:"https://zdnet.com"},
{cli:"abcn",ver:"World",sub:"ABC is an American broadcast television network that is property of Walt Disney.",api:"https://abcnews.go.com/abcnews/internationalheadlines",ext:"https://abc.com"},
{cli:"bbct",ver:"World",sub:"BBC is the world’s leading public service broadcaster.",api:"http://feeds.bbci.co.uk/news/rss.xml",ext:"https://bbc.com"},
{cli:"blom",ver:"World",sub:"Bloomberg delivers business and markets news, data, analysis, and video.",api:"https://www.bloomberg.com/view/rss",ext:"https://bloomberg.com"},
{cli:"cbsn",ver:"World",sub:"CBS is a media company that creates and distributes industry-leading content.",api:"https://www.cbsnews.com/latest/rss/world",ext:"https://cbsnews.com"},
{cli:"cnwn",ver:"World",sub:"CNBC Latest World News, latest headlines from around the world.",api:"https://www.cnbc.com/id/100727362/device/rss/rss.html",ext:"https://cnbc.com/world"},
{cli:"cnni",ver:"World",sub:"CNN is among the world's leaders in online news and information delivery.",api:"http://rss.cnn.com/rss/cnn_topstories.rss",ext:"https://cnn.com"},
{cli:"daly",ver:"World",sub:"Daily Mail is a British daily middle-market newspaper published in London.",api:"https://www.dailymail.co.uk/articles.rss",ext:"https://dailymail.co.uk"},
{cli:"dgtn",ver:"World",sub:"Digital Trends’ team of experienced staffers provide the latest news.",api:"https://www.digitaltrends.com/news/feed",ext:"https://digitaltrends.com/news"},
{cli:"drdg",ver:"World",sub:"Drudge Report consists mainly of news stories from other outlets.",api:"http://feeds.feedburner.com/DrudgeReportFeed",ext:"https://drudgereport.com"},
{cli:"foxn",ver:"World",sub:"Fox News Breaking News, Latest News and Current News.",api:"http://feeds.foxnews.com/foxnews/latest",ext:"https://foxnews.com"},
{cli:"goog",ver:"World",sub:"Google is a multinational technology company that specializes in Internet-related services and products.",api:"https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",ext:"https://news.google.com"},
{cli:"mirr",ver:"World",sub:"Mirror.co.uk World headlines, pictures, analysis, opinion and video.",api:"https://www.mirror.co.uk/news/us-news/?service=rss",ext:"https://mirror.co.uk/news/us-news"},
{cli:"merc",ver:"World",sub:"Mercury News is passionate about serving readers in Silicon Valley and its global technology community.",api:"https://www.mercurynews.com/feed",ext:"https://mercurynews.com"},
{cli:"msnb",ver:"World",sub:"MSN is a web portal of Internet services and apps for Windows and mobile devices.",api:"http://rss.msn.com",ext:"https://msn.com"},
{cli:"nbcn",ver:"World",sub:"NBC News is the news division of the American broadcast television network NBC.",api:"http://feeds.nbcnews.com/nbcnews/public/news",ext:"https://nbcnews.com"},
{cli:"nprn",ver:"World",sub:"NPR is an independent, nonprofit media organization that was founded to create a more informed public.",api:"https://www.npr.org/rss/rss.php?id=1019",ext:"https://npr.org"},
{cli:"pbsn",ver:"World",sub:"Public Broadcasting Service is an American public broadcaster and television program distributor.",api:"https://www.pbs.org/newshour/feeds/rss/headlines",ext:"https://pbs.org"},
{cli:"rwor",ver:"World",sub:"World News subreddit with latest headlines from around the world.",api:"https://www.reddit.com/r/worldnews/.rss",ext:"https://reddit.com/r/worldnews"},
{cli:"rtwn",ver:"World",sub:"RT delivers latest news on current events from around the world.",api:"https://www.rt.com/rss",ext:"https://rt.com"},
{cli:"gate",ver:"World",sub:"San Francisco Gate is the Hearst-owned website sister-site of the San Francisco Chronicle.",api:"https://www.sfgate.com/rss/feed/Business-and-Technology-News-448.php",ext:"https://sfgate.com/technology"},
{cli:"sptc",ver:"World",sub:"Sputnik is a major new media brand with modern multimedia centers in dozens of countries.",api:"https://sputniknews.com/export/rss2/archive/index.xml",ext:"https://sputniknews.com"},
{cli:"nswk",ver:"World",sub:"Newsweek provides the latest news about international issues, technology, business, culture and politics.",api:"https://www.newsweek.com/rss",ext:"https://newsweek.com"},
{cli:"nydw",ver:"World",sub:"New York Daily News news coverage, sports, entertainment news, celebrity gossip, autos, videos and photos.",api:"https://www.nydailynews.com/cmlink/NYDN.News.World.rss",ext:"https://www.nydailynews.com/news/world"},
{cli:"nypt",ver:"World",sub:"New York Post is a daily newspaper in New York City.",api:"https://nypost.com/feed",ext:"https://nypost.com"},
{cli:"tage",ver:"World",sub:"The Age National News from Australia, World News, Business News and Breaking News stories.",api:"https://www.theage.com.au/rss/feed.xml",ext:"https://www.theage.com.au"},
{cli:"time",ver:"World",sub:"Time Magazine is one of the most authoritative and informative guides to what is happening in the world.",api:"http://feeds.feedburner.com/time/topstories?format=xml",ext:"https://time.com"},
{cli:"upif",ver:"World",sub:"United Press International is a leading provider of news, photos and information.",api:"https://rss.upi.com/news/news.rss",ext:"https://upi.com"},
{cli:"ustd",ver:"World",sub:"USA Today delivers local and national news, sports, entertainment, finance, technology, and more.",api:"http://rssfeeds.usatoday.com/usatoday-newstopstories&x=1",ext:"https://www.usatoday.com"},
{cli:"vice",ver:"World",sub:"Vice Original reporting and documentaries on everything that matters in the world.",api:"https://www.vice.com/en_us/rss",ext:"https://vice.com"},
{cli:"wasw",ver:"World",sub:"Washington Times World News, Middle East News, Afghanistan War.",api:"https://www.washingtontimes.com/rss/headlines/news/world",ext:"https://washingtontimes.com/news/world"}
}
