var menu=[
{ver:"News",des:"ABC KFSN-TV Local Fresno and national news.",api:"https://abc30.com/feed",ext:"https://abc30.com"},
{ver:"News",des:"KSEE24 CBS47 your central valley in Fresno, California.",api:"https://yourcentralvalley.com/feed",ext:"https://www.yourcentralvalley.com"},
{ver:"News",des:"ABC WCVB Boston News, Weather and Sports online, anytime.",api:"https://www.wcvb.com/topstories-rss",ext:"https://wcvb.com"},
{ver:"News",des:"CBS WBZ-TV Boston Local Breaking News From Boston, Mass.",api:"https://boston.cbslocal.com/feed",ext:"https://boston.cbslocal.com/feed"},
{ver:"News",des:"NBC WBTS-CD Boston Local news, national news and Boston breaking news stories.",api:"https://www.nbcboston.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcboston.com"},
{ver:"News",des:"ABC7 Chicago's Breaking News covering Weather, Traffic and Sports.",api:"https://abc7chicago.com/feed",ext:"https://abc7chicago.com"},
{ver:"News",des:"CBS WBBM-TV Chicago Local television station.",api:"https://chicago.cbslocal.com/feed",ext:"https://chicago.cbslocal.com"},
{ver:"News",des:"NBC WMAQ-TV Chicago's latest weather, traffic, entertainment and politicals.",api:"https://www.nbcchicago.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcchicago.com"},
{ver:"News",des:"CBS KTVT Dallas Fort-Worth Texas breaking news, weather, traffic, and sports.",api:"https://dfw.cbslocal.com/feed",ext:"https://dfw.cbslocal.com"},
{ver:"News",des:"NBC KXAS-TV Dallas Fort-Worth News, Weather, Sports, Business, Lifestyle, Traffic and Health.",api:"https://www.nbcdfw.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://www.nbcdfw.com"},
{ver:"News",des:"ABC KTRK-TV Houston breaking news from Houston and the surrounding neighborhoods.",api:"https://abc13.com/feed",ext:"https://abc13.com"},
{ver:"News",des:"ABC KSAT-TV San Antonio Latest, news, weather and sports.",api:"https://www.ksat.com/arcio/rss/category/news/national/?size=10",ext:"https://www.ksat.com"},
{ver:"News",des:"ABC7 Covers Los Angeles news, weather, sports, traffic and live video.",api:"https://abc7.com/feed",ext:"https://abc7.com"},
{ver:"News",des:"CBS KCBS-TV Los Angeles news, Sports, Weather, Traffic and the Best of LA and OC.",api:"https://losangeles.cbslocal.com/feed",ext:"https://losangeles.cbslocal.com"},
{ver:"News",des:"NBC KNBC Los Angeles Weather, Traffic, Politics, Sports, and Entertainment News.",api:"https://www.nbclosangeles.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbclosangeles.com"},
{ver:"News",des:"ABC10 Miami, Florida Breaking News and Headlines.",api:"https://www.local10.com/feeds/rssFeed/feedServlet?obfType=GMG_RSS_TEASERS&siteId=800006&categoryId=80041&nbRows=10",ext:"https://local10.com"},
{ver:"News",des:"CBS WFOR-TV Miami a Full Service Television Station in Miami and Fort Lauderdale.",api:"https://miami.cbslocal.com/feed",ext:"https://miami.cbslocal.com"},
{ver:"News",des:"NBC WTVJ Florida Local News, National News and Breaking News Stories.",api:"https://www.nbcmiami.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcmiami.com"},
{ver:"News",des:"ABC7 San Francisco Local News and Headlines.",api:"https://abc7news.com/feed",ext:"https://abc7news.com"},
{ver:"News",des:"CBS KPIX San Francisco News, Sports, Weather, Traffic and the Best of San Francisco.",api:"https://sanfrancisco.cbslocal.com/feed",ext:"https://sanfrancisco.cbslocal.com"},
{ver:"News",des:"NBC KNTV San Franscisco Local Television Station in the Bay Area market.",api:"https://www.nbcbayarea.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcbayarea.com"},
{ver:"News",des:"ABC7 New York covering New York City, New Jersey, and Long Island.",api:"https://abc7ny.com/feed",ext:"https://abc7ny.com"},
{ver:"News",des:"CBS WCBS-TV New York City Digital Streaming News Service, It's always on.",api:"https://newyork.cbslocal.com/feed",ext:"https://newyork.cbslocal.com"},
{ver:"News",des:"NBC WNBC New York Weather, Traffic, Entertainment and Health.",api:"https://www.nbcnewyork.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcnewyork.com"},
{ver:"News",des:"NBC WRC-TV Washington D.C. News, Weather, Traffic, Entertainment and Health.",api:"https://www.nbcwashington.com/news/top-stories/?rss=y&embedThumb=y&summary=y",ext:"https://nbcwashington.com"},
{ver:"News",des:"CBS WUSA licensed to the capital city of Washington, District of Columbia.",api:"http://rssfeeds.wusa9.com/wusa-news&x=1",ext:"https://wusa9.com"},
{ver:"Media",des:"ABC Entertainment Latest Celebrity News, Videos & Photos.",api:"https://abcnews.go.com/abcnews/entertainmentheadlines",ext:"https://abcnews.go.com/entertainment"},
{ver:"Media",des:"AOL Latest Headlines in Business, Entertainment, Politics, World News, Tech, Sports, and Video.",api:"https://www.aol.com/rss",ext:"https://aol.com"},
{ver:"Media",des:"AV Club is an Entertainment Website that examines Films, Music, Television, Books, and Games.",api:"https://www.avclub.com/rss",ext:"https://www.avclub.com"},
{ver:"Media",des:"BBC News Entertainment, Lifestyle, and Arts.",api:"http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",ext:"https://bbc.com/news/entertainment_and_arts"},
{ver:"Media",des:"BuzzFeed is an American Internet Media, News and Entertainment Company.",api:"https://www.buzzfeed.com/index.xml",ext:"https://www.buzzfeed.com"},
{ver:"Media",des:"ComingSoon.net has New Movies, Movie Trailers, TV, Digital, Blu-ray & Video Game News!",api:"https://www.comingsoon.net/feed",ext:"https://comingsoon.net"},
{ver:"Media",des:"CBS Entertainment Latest Celebrity News, Movies, TV shows, and more.",api:"https://www.cbsnews.com/latest/rss/entertainment",ext:"https://cbsnews.com/latest/rss/entertainment"},
{ver:"Media",des:"Celebrity Hub subreddit Pictures and GIFs of Actresses, Singers, Models, Athletes and Celebs.",api:"https://reddit.com/r/celebhub/.rss",ext:"https://reddit.com/r/celebhub"},
{ver:"Media",des:"CNN Entertainment News Celebrities, Movies, TV, and Music.",api:"http://rss.cnn.com/rss/cnn_showbiz.rss",ext:"https://cnn.com/entertainment"},
{ver:"Media",des:"Deadline is the first to break Up-to-the-Minute Entertainment, Hollywood and Media News.",api:"https://deadline.com/feed",ext:"https://deadline.com"},
{ver:"Media",des:"Digital Trends Movie reviews, TV Show recaps, previews, and news.",api:"https://www.digitaltrends.com/movies/feed/",ext:"https://digitaltrends.com/movies"},
{ver:"Media",des:"Daily Beast is a News and Opinion Website focusing on Politics, Power and Entertainment Culture.",api:"https://feeds.thedailybeast.com/summary/rss/articles",ext:"https://www.thedailybeast.com"},
{ver:"Media",des:"Entertainment subreddit has News and Discussion of the Entertainment Industry.",api:"https://reddit.com/r/entertainment/.rss",ext:"https://reddit.com/r/entertainment"},
{ver:"Media",des:"Esquire is your destination for the Latest Entertainment News Headlines.",api:"https://www.esquire.com/rss/entertainment.xml",ext:"https://esquire.com"},
{ver:"Media",des:"Google Entertainment Headlines, Opinions, and News.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=film+movie+music+art+entertainment&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{ver:"Media",des:"IndieWire has Grown Over Decades as a Preeminent Source for Film and Television News.",api:"https://www.indiewire.com/feed",ext:"https://www.indiewire.com"},
{ver:"Media",des:"Inverse Covers the Latest News on Science, Innovation, Entertainment, Technology and Culture.",api:"https://www.inverse.com/feed/articles/1.rss",ext:"https://www.inverse.com"},
{ver:"Media",des:"Just Jared Jr. is the Definitive Site for Celebrity News.",api:"http://www.justjared.com/feed",ext:"http://justjared.com"},
{ver:"Media",des:"Movies subreddit News and Discussion about Major Motion Pictures.",api:"https://reddit.com/r/movies/.rss",ext:"https://reddit.com/r/movies"},
{ver:"Media",des:"Metacritic aggregates Reviews of Films, TV Shows, Music Albums, and Video Games.",api:"https://www.metacritic.com/rss/features",ext:"https://www.metacritic.com"},
{ver:"Media",des:"Movieweb is the Fastest, Most Complete Movie & TV Coverage on the Planet.",api:"https://movieweb.com/rss/all-news",ext:"https://movieweb.com"},
{ver:"Media",des:"People is an American Weekly Magazine of Celebrity and Human-Interest Stories.",api:"https://people.com/tag/news/feed",ext:"https://people.com"},
{ver:"Media",des:"PerezHilton is known for posts covering Gossip Items about Celebrities.",api:"https://perezhilton.com/feed",ext:"https://perezhilton.com"},
{ver:"Media",des:"RollingStone Magazine the authority on Music, Entertainment, Politics and Entertainment Culture.",api:"https://www.rollingstone.com/feed",ext:"https://rollingstone.com"},
{ver:"Media",des:"Snopes Fact Checking and Original Investigative Reporting.",api:"https://www.snopes.com/feed",ext:"https://www.snopes.com"},
{ver:"Media",des:"NY Post Entertainment Latest and Breaking News on Celebrities, Movies, and TV shows.",api:"https://nypost.com/entertainment/feed",ext:"https://nypost.com/entertainment/feed"}, 
{ver:"Media",des:"TMZ is a tabloid News website that was a Collaboration between AOL and Telepictures Productions.",api:"https://www.tmz.com/rss.xml",ext:"https://tmz.com"},
{ver:"Media",des:"Uproxx is an Entertainment and Entertainmentular Culture News website.",api:"http://feeds.feedburner.com/uproxx/features",ext:"https://uproxx.com"},
{ver:"Media",des:"Vanity Fair is a magazine of Entertainmentular Culture, Fashion, and Current Affairs.",api:"https://www.vanityfair.com/feed/rss",ext:"https://vanityfair.com"},
{ver:"Media",des:"Video subreddit the best place for Video content of all kinds.",api:"https://reddit.com/r/videos/.rss",ext:"https://reddit.com/r/videos"},
{ver:"Media",des:"Washington Times Show Business News and Entertainment News.",api:"https://www.washingtontimes.com/rss/headlines/culture/entertainment",ext:"https://washingtontimes.com/culture/entertainment"},
{ver:"Media",des:"Yahoo Entertainment News, Celebrity, Movie, TV.",api:"https://www.yahoo.com/entertainment/rss",ext:"https://yahoo.com/entertainment"},
{ver:"Media",des:"Yahoo Celebrity for the Latest News and Gossip on the World's Celebrities.",api:"https://www.yahoo.com/celebrity/rss",ext:"https://yahoo.com/celebrity"},
{ver:"Social",des:"Apple subreddit to discuss Apple Devices and Software, including News, Rumors, Opinions and Analysis.",api:"https://reddit.com/r/apple/.rss",ext:"https://reddit.com/r/apple"},
{ver:"Social",des:"Android subreddit News, Reviews, Tips, and Discussions about Rooting, Tutorials, and Apps.",api:"https://reddit.com/r/android/.rss",ext:"https://reddit.com/r/android"},
{ver:"Social",des:"Arch Linux BBS is a Linux distribution for computers based on x86-64 architectures.",api:"https://bbs.archlinux.org/extern.php?type=rss",ext:"http://bbs.archlinux.org"},
{ver:"Social",des:"Arch Linux subreddit discusses Topics revolving around Arch Linux.",api:"https://reddit.com/r/archlinux/.rss",ext:"https://reddit.com/r/archlinux"},
{ver:"Social",des:"BSD subreddit about Berkeley Software Distribution an operating system based on Unix.",api:"https://reddit.com/r/bsd/.rss",ext:"https://reddit.com/r/bsd"},
{ver:"Social",des:"Command Line subreddit with questions and answers.",api:"https://reddit.com/r/commandline/.rss",ext:"https://reddit.com/r/commandline"},
{ver:"Social",des:"Computer subreddit with Questions and Answers.",api:"https://reddit.com/r/computers/.rss",ext:"https://reddit.com/r/computers"},
{ver:"Social",des:"Debian Linux subreddit covers Topics revolving around Debian OS.",api:"https://reddit.com/r/debian/.rss",ext:"https://reddit.com/r/debian"},
{ver:"Social",des:"Dev Ops subreddit with 117,000 members created in 2010.",api:"https://reddit.com/r/devops/.rss",ext:"https://reddit.com/r/devops"},
{ver:"Social",des:"DIY board discusses Projects, asks Questions, covers Topics, exchanges Ideas and Techniques.",api:"http://boards.4channel.org/diy/index.rss",ext:"http://boards.4channel.org/diy"},
{ver:"Social",des:"Fedora subreddit Community for Users, Developers and People interested in Fedora.",api:"https://reddit.com/r/fedora/.rss",ext:"https://reddit.com/r/fedora"},
{ver:"Social",des:"G Technology is a board that discusses Technology.",api:"http://boards.4chan.org/g/index.rss",ext:"http://boards.4channel.org/g/"},
{ver:"Social",des:"Games subreddit aims to provide a place for Informative and interesting Gaming Content.",api:"http://reddit.com/r/games/.rss",ext:"https://reddit.com/r/games"},
{ver:"Social",des:"Google Linux combination of top resources for Linux.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=linux&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{ver:"Social",des:"Google Social news from top Social Media platforms.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=social+facebook+twitter+instagram+tiktok+snapchat+news&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{ver:"Social",des:"Hacker News is a reader ran headline submission news purveyor.",api:"https://news.ycombinator.com/rss",ext:"https://news.ycombinator.com"},
{ver:"Social",des:"Hacking subreddit dedicated to Hacking and Hackers.",api:"https://reddit.com/r/hacking/.rss",ext:"https://reddit.com/r/hacking"},
{ver:"Social",des:"iOS subreddit for everything Apple iOS.",api:"https://reddit.com/r/ios/.rss",ext:"https://reddit.com/r/ios"},
{ver:"Social",des:"Javascript subreddit all about the JavaScript Programming Language!",api:"https://reddit.com/r/javascript/.rss",ext:"https://reddit.com/r/javascript"},
{ver:"Social",des:"Linux subreddit discusses topics evolving around Linux.",api:"https://reddit.com/r/linux/.rss",ext:"https://reddit.com/r/linux"},
{ver:"Social",des:"Math subreddit with nearly one million members.",api:"https://reddit.com/r/math/.rss",ext:"https://reddit.com/r/math"},
{ver:"Social",des:"Node subreddit all about NodeJs, created in 2009 with 141,000 members.",api:"https://reddit.com/r/node/.rss",ext:"https://reddit.com/r/node"},
{ver:"Social",des:"Programming subreddit shares user submitted articles on Programming.",api:"https://reddit.com/r/programming/.rss",ext:"https://reddit.com/r/programming"},
{ver:"Social",des:"Python subreddit about the Dynamic, Interpreted, Interactive, Object-Oriented, extensible language Python.",api:"https://reddit.com/r/python/.rss",ext:"https://reddit.com/r/python"},
{ver:"Social",des:"Redhat subreddit discussion for Red Hat and Red Hat technologies!",api:"https://reddit.com/r/redhat/.rss",ext:"https://reddit.com/r/redhat"},
{ver:"Social",des:"Science subreddit Read about the latest advances in astronomy, biology, medicine, physics, and social science.",api:"https://reddit.com/r/science/.rss",ext:"https://reddit.com/r/science"},
{ver:"Social",des:"Security subreddit has been around for 11 years and has 93,000 subscribers.",api:"https://reddit.com/r/security/.rss",ext:"https://reddit.com/r/security"}, 
{ver:"Social",des:"Slashdot is a social News website that originally billed itself as News for Nerds.",api:"http://rss.slashdot.org/Slashdot/slashdot",ext:"https://slashdot.org"},
{ver:"Social",des:"Sysadmin subreddit dedicated to the Profession of Computer System Administration.",api:"https://reddit.com/r/sysadmin/.rss",ext:"https://reddit.com/r/sysadmin"},
{ver:"Social",des:"Tech subreddit the Intelligent Discussion of Innovations and changes to Technology.",api:"https://reddit.com/r/tech/.rss",ext:"https://reddit.com/r/tech"},
{ver:"Social",des:"Technology subreddit with submitted articles.",api:"https://reddit.com/r/technology/.rss",ext:"https://reddit.com/r/technology"},
{ver:"Social",des:"Steam subreddit for members of the Steam Community.",api:"https://reddit.com/r/steam/.rss",ext:"https://reddit.com/r/steam"},
{ver:"Social",des:"Ubuntu subreddit or News, Information and General Discussion related to Ubuntu..",api:"https://reddit.com/r/ubuntu/.rss",ext:"https://reddit.com/r/ubuntu"},
{ver:"Social",des:"Unix subreddit *NIX Desktops, Themes, and nifty Configurations",api:"https://reddit.com/r/unixporn/.rss",ext:"https://reddit.com/r/unixporn"},
{ver:"Social",des:"Wallpaper subreddit Computer Desktops and Background Images.",api:"https://reddit.com/r/wallpaper/.rss",ext:"https://reddit.com/r/wallpaper"},
{ver:"Social",des:"Wallpapers subreddit Work-safe wallpapers from all over!",api:"https://reddit.com/r/wallpapers/.rss",ext:"https://reddit.com/r/wallpapers"},
{ver:"Social",des:"Wallpapers General including Desktops, Builds, Mobile, Mods, NO Requests.",api:"http://boards.4chan.org/wg/index.rss",ext:"http://boards.4chan.org/wg"},
{ver:"Social",des:"Windows subreddit about the Operating System released by Microsoft as part of the Windows NT family.",api:"https://reddit.com/r/windows/.rss",ext:"https://reddit.com/r/windows"},
{ver:"Sport",des:"ABC Sports the Latest Sports News, Articles and more.",api:"https://abcnews.go.com/abcnews/sportsheadlines",ext:"https://abcnews.go.com/Sports"},
{ver:"Sport",des:"Barstool Sports is a sports & pop culture blog covering the latest news and viral highlights.",api:"https://cms.barstoolsports.com/feed",ext:"https://www.barstoolsports.com"}, 
{ver:"Sport",des:"Barstool Sports subreddit By the Common Man, For the Common Man.",api:"https://reddit.com/r/barstoolsports/.rss",ext:"https://reddit.com/r/barstoolsports"},
{ver:"Sport",des:"Baseball subreddit for the Bat-and-Ball Sport played between two teams of nine players.",api:"https://reddit.com/r/baseball/.rss",ext:"https://reddit.com/r/baseball"},
{ver:"Sport",des:"BBC Sports News from around the world.",api:"http://feeds.bbci.co.uk/sport/rss.xml",ext:"https://bbc.com/sport"},
{ver:"Sport",des:"BJPENN has become one of the most reliable destinations for your MMA and UFC needs. ",api:"https://www.bjpenn.com/feed",ext:"https://bjpenn.com"},
{ver:"Sport",des:"Bleacher Report is a website that focuses on sport and sports culture.",api:"https://bleacherreport.com/articles/feed",ext:"https://bleacherreport.com"},
{ver:"Sport",des:"CBS Sports is an American Sports News website operated by CBS Interactive.",api:"https://rss.cbssports.com/rss/headlines",ext:"https://cbssports.com"},
{ver:"Sport",des:"CFB subreddit forum for all things college football focusing on NCAA football.",api:"https://reddit.com/r/cfb/.rss",ext:"https://reddit.com/r/cfb"},
{ver:"Sport",des:"CNN Sports catalogues the Latest News from around the World.",api:"http://rss.cnn.com/rss/edition_sport.rss",ext:"https://cnn.com/sport"},
{ver:"Sport",des:"Deadspin brings you the Latest Sports News, Stories, Videos, and more.",api:"https://deadspin.com/rss",ext:"https://deadspin.com"},
{ver:"Sport",des:"Digital Trends' world of cars, speed and power.",api:"https://www.digitaltrends.com/cars/feed",ext:"https://digitaltrends.com/cars"},
{ver:"Sport",des:"ESPN is a cable network that plays Live and taped Sporting Events.",api:"https://www.espn.com/espn/rss/news",ext:"https://espn.com"},
{ver:"Sport",des:"ESPN NFL Football News, Scores, Stats, Standings, Fantasy games, and more.",api:"http://www.espn.com/espn/rss/nfl/news",ext:"https://espn.com/nfl"},
{ver:"Sport",des:"ESPN NBA Team Stats, Schedules, Rosters, Depth charts and more.",api:"http://www.espn.com/espn/rss/nba/news",ext:"https://espn.com/nba"},
{ver:"Sport",des:"ESPN MLB Baseball News, Scores, Stats, Standings, Fantasy games, and more.",api:"http://www.espn.com/espn/rss/mlb/news",ext:"https://espn.com/mlb"},
{ver:"Sport",des:"ESPN NHL Hockey News, Scores, Stats, Standings, Fantasy games, and more.",api:"http://www.espn.com/espn/rss/nhl/news",ext:"https://espn.com/nhl"},
{ver:"Sport",des:"ESPN CFB National Collegiate Athletic Association Division I Football Bowl Subdivision.",api:"http://www.espn.com/espn/rss/ncf/news",ext:"https://espn.com/ncf"},
{ver:"Sport",des:"Football subreddit Discusses and Headlines topics around football.",api:"https://reddit.com/r/football/.rss",ext:"https://reddit.com/r/football"},
{ver:"Sport",des:"Fox Sports is a wide array of Multi-Platform US-based Sports Assets.",api:"https://api.foxsports.com/v1/rss?partnerKey=zBaFxRyGKCfxBagJG9b8pqLyndmvo7UU",ext:"https://foxsports.com"},
{ver:"Sport",des:"Goal.com Latest Soccer News, Live Scores, Results, Rumours, and Transfers.",api:"https://www.goal.com/feeds/en/news",ext:"https://goal.com"},
{ver:"Sport",des:"Google Sports NBA, MLB, MMA, NFL, NHL, NCAA.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=sports+nba+nfl+ncaa+nhl+mlb+mma+cfb&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{ver:"Sport",des:"Hockey subreddit NHL, AHL, KHL, NWHL, IIHF and every other Hockey League.",api:"https://reddit.com/r/hockey/.rss",ext:"https://reddit.com/r/hockey"},
{ver:"Sport",des:"Jalopnik is a Sews site about Cars, Racing, Transportation, Airplanes, and Motorcycles",api:"https://jalopnik.com/rss",ext:"https://jalopnik.com"},
{ver:"Sport",des:"MLB subreddit covers Major League Baseball Headlines and News.",api:"https://reddit.com/r/mlb/.rss",ext:"https://reddit.com/r/mlb"},
{ver:"Sport",des:"MLB.com is the official site of Major League Baseball.",api:"https://www.mlb.com/feeds/news/rss.xml",ext:"https://mlb.com"},
{ver:"Sport",des:"MMAJunkie Radio is a weekly Internet radio show broadcast from Las Vegas, Nevada.",api:"https://mmajunkie.com/news/feed",ext:"https://mmajunkie.com"},
{ver:"Sport",des:"MMA.news offers coverage of the MMA world with original content.",api:"https://www.mmanews.com/feed",ext:"https://mmanews.com"},
{ver:"Sport",des:"MMA subreddit for all things Mixed Martial Arts.",api:"https://reddit.com/r/MMA/.rss",ext:"https://reddit.com/r/MMA"},
{ver:"Sport",des:"NBC Sports is responsible for the televising of many Sports Events.",api:"https://sports.nbcsports.com/feed",ext:"https://nbcsports.com"},
{ver:"Sport",des:"NFL subreddit covers National Football League News and Discussion.",api:"https://reddit.com/r/nfl/.rss",ext:"https://reddit.com/r/nfl"},
{ver:"Sport",des:"NY Post Sports including Scores, Trade Rumors and Standings for Baseball, Football, and Basketball.",api:"https://nypost.com/sports/feed",ext:"https://nypost.com/sports"},
{ver:"Sport",des:"NCAA FBS College Football Headlines.",api:"https://www.ncaa.com/news/football/fbs/rss.xml",ext:"https://ncaa.com/sports/football/fbs"},
{ver:"Sport",des:"RT Sport delivers Latest News on Sports from around the world.",api:"https://www.rt.com/rss/sport",ext:"https://rt.com/sport"},
{ver:"Sport",des:"Sports Illustrated Top Stories is a Weekly Sports Magazine that originated in 1954.",api:"https://www.si.com/rss/si_topstories.rss",ext:"https://si.com"},
{ver:"Sport",des:"Sports Illustrated Fantasy Drafts, Mockups, Trades, Rumors, Deadlines.",api:"https://www.si.com/rss/si_fantasy.rss",ext:"https://www.si.com/fantasy"},
{ver:"Sport",des:"Sports Illustrated MLB News, Scores, Stats, and Fantasy.",api:"https://www.si.com/rss/si_mlb.rss",ext:"https://www.si.com/mlb"},
{ver:"Sport",des:"Sports Illustrated MMA Fight Previews, Weigh-Ins and Face-Offs.",api:"https://www.si.com/rss/si_mma.rss",ext:"https://www.si.com/mma"},
{ver:"Sport",des:"Sports Illustrated NBA Headlines and Analysis.",api:"https://www.si.com/rss/si_nba.rss",ext:"https://www.si.com/nba"},
{ver:"Sport",des:"Sports Illustrated NCAA College Football Headlines and Stories.",api:"https://www.si.com/rss/si_ncaaf.rss",ext:"https://www.si.com/college/college-football"},
{ver:"Sport",des:"Sports Illustrated NFL Latest News, Scores, Schedules, and Fantasy Analysis.",api:"https://www.si.com/rss/si_nfl.rss",ext:"https://www.si.com/nfl"},
{ver:"Sport",des:"Sports Illustrated Soccer Stories, News, Headlines, and Analysis.",api:"https://www.si.com/rss/si_soccer.rss",ext:"https://www.si.com/soccer"},
{ver:"Sport",des:"Sports Illustrated Tennis Matches, Tournaments, Previews, and more.",api:"https://www.si.com/rss/si_tennis.rss",ext:"https://www.si.com/tennis"},
{ver:"Sport",des:"Sports is a board that discusses International Sports.",api:"http://boards.4chan.org/sp/index.rss",ext:"http://boards.4channel.org/sp/"},
{ver:"Sport",des:"Sporting News was established in 1886 as a weekly U.S. Magazine.",api:"http://www.sportingnews.com/us/rss",ext:"http://sportingnews.com"},
{ver:"Sport",des:"Sports subreddit for all the Latest Headlines and Discussion in Sports.",api:"https://reddit.com/r/sports/.rss",ext:"https://reddit.com/r/sports"},
{ver:"Sport",des:"Telegraph.co.uk Sport news from around the world.",api:"https://www.telegraph.co.uk/sport/rss.xml",ext:"https://www.telegraph.co.uk/sport"},
{ver:"Sport",des:"Tennis subreddit discusses Tennis, from Tour Professionals to Recreational Players.",api:"https://reddit.com/r/tennis/.rss",ext:"https://reddit.com/r/tennis"},
{ver:"Sport",des:"The Score NFL is the Ultimate, Personalized Mobile Sports Experience.",api:"https://feeds.thescore.com/nfl.rss",ext:"https://thescore.com/nfl/news"},
{ver:"Sport",des:"The Score MLB is the Ultimate, Personalized Mobile Sports Experience.",api:"https://feeds.thescore.com/mlb.rss",ext:"https://thescore.com/mlb/news"},
{ver:"Sport",des:"The Score MMA is the Ultimate, Personalized Mobile Sports Experience.",api:"https://feeds.thescore.com/mma.rss",ext:"https://thescore.com/mma/news"},
{ver:"Sport",des:"The Underground is a MMA website that features Daily MMA News.",api:"http://www.mixedmartialarts.com/news/feed",ext:"http://mixedmartialarts.com"},
{ver:"Sport",des:"Tiebreaker Sports News Headlines from around the world.",api:"https://www.tiebreaker.com/feed",ext:"https://www.tiebreaker.com"},
{ver:"Sport",des:"UFC is an American Mixed Martial Arts promotion Company based in Las Vegas, Nevada.",api:"https://www.ufc.com/rss/news",ext:"https://ufc.com"},
{ver:"Sport",des:"Vice Fightland is a website covering Mixed Martial Arts, MMA.",api:"http://fightland.vice.com/rss",ext:"http://fightland.vice.com"},
{ver:"Sport",des:"Yahoo! Sports has Comprehensive  News, Scores, Standings, Fantasy Games, Rumors, and more.",api:"https://sports.yahoo.com/rss",ext:"https://sports.yahoo.com"},
{ver:"Technology",des:"ABC Technology for Latest Science News, Technology News, and more.",api:"https://abcnews.go.com/abcnews/technologyheadlines",ext:"https://abcnews.go.com/technology"},
{ver:"Technology",des:"Ars Technica has became a Trusted Source for Technology News.",api:"http://feeds.arstechnica.com/arstechnica/index?format=xml",ext:"https://arstechnica.com"},
{ver:"Technology",des:"BBC Technology News, Articles, and more.",api:"http://feeds.bbci.co.uk/news/technology/rss.xml",ext:"https://bbc.co.uk/news/technology"},
{ver:"Technology",des:"BetaNews is a leading source of Technology News and Analysis.",api:"http://feeds.betanews.com/bn",ext:"https://betanews.com"},
{ver:"Technology",des:"BGR is a destination for News focused on the Consumer Electronics Market.",api:"https://bgr.com/tech/feed",ext:"https://bgr.com/tech"},
{ver:"Technology",des:"Boston Technology including MIT, Auto, Social Media, and Business.",api:"https://www.boston.com/tag/technology/feed",ext:"https://www.boston.com/tag/technology"},
{ver:"Technology",des:"Business Insider is a Growing Business site with Financial, Media, and Tech.",api:"https://www.businessinsider.com/rss",ext:"https://businessinsider.com"},
{ver:"Technology",des:"CBS Technology on Social Media, Artificial Intelligence, Computers and more.",api:"https://www.cbsnews.com/latest/rss/technology",ext:"https://cbsnews.com/technology"},
{ver:"Technology",des:"CNBC is an American elevision News channel that is owned by NBC Universal.",api:"https://www.cnbc.com/id/19854910/device/rss/rss.html",ext:"https://cnbc.com/technology"},
{ver:"Technology",des:"CNET is an American media website that publishes Reviews, News, Articles, and Videos on Technology.",api:"https://www.cnet.com/rss/news",ext:"https://cnet.com"},
{ver:"Technology",des:"Computer Weekly stands out from the many Technology News Websites.",api:"https://www.computerweekly.com/rss/RSS-Feed.xml",ext:"https://computerweekly.com"},
{ver:"Technology",des:"Digital Trends is a Technology News, Lifestyle, and Information Website.",api:"https://www.digitaltrends.com/feed",ext:"https://digitaltrends.com"},
{ver:"Technology",des:"Engadget is a Technology blog Network with Daily Coverage of Gadgets and Consumer Electronics.",api:"https://www.engadget.com/rss.xml",ext:"https://engadget.com"},
{ver:"Technology",des:"EuroGamer Gaming news, reviews and the best long-form journalism.",api:"https://www.eurogamer.net/?format=rss&type=article",ext:"https://www.eurogamer.net"},
{ver:"Technology",des:"Forbes is a Global Media Company, focusing on Business, Investing, and Technology.",api:"https://www.forbes.com/most-popular/feed",ext:"https://forbes.com"},
{ver:"Technology",des:"Gaming on Linux Latest Articles and Games.",api:"https://www.gamingonlinux.com/article_rss.php",ext:"https://gamingonlinux.com"},
{ver:"Technology",des:"GeekWire is an American Technology News site that covers Startups and Established Technology Companies.",api:"https://www.geekwire.com/feed",ext:"https://geekwire.com"},
{ver:"Technology",des:"Gizmodo is a Design, Technology, Science and Science Fiction website.",api:"https://gizmodo.com/rss",ext:"https://gizmodo.com"},
{ver:"Technology",des:"gHacks the Independent Rechnology News blog.",api:"https://www.ghacks.net/feed",ext:"https://ghacks.net"},
{ver:"Technology",des:"Google Technology News, Opinion, and Analysis.",api:"https://news.google.com/rss/search?cf=all&pz=1&q=technology&hl=en-US&gl=US&ceid=US:en",ext:"https://google.com"},
{ver:"Technology",des:"Hackaday serves up Fresh Hacks Every Day from around the Internet.",api:"https://hackaday.com/feed",ext:"https://hackaday.com"},
{ver:"Technology",des:"Independent.co.uk for Latest Gadgets and Tech News.",api:"http://www.independent.co.uk/life-style/gadgets-and-tech/rss",ext:"https://independent.co.uk/life-style/gadgets-and-tech"},
{ver:"Technology",des:"InfoWorld is an Information Technology Media Business.",api:"https://www.infoworld.com/index.rss",ext:"https://infoworld.com"}, 
{ver:"Technology",des:"Kotaku is a News and Opinion site about Games and things serious Gamers care about.",api:"https://kotaku.com/rss",ext:"https://kotaku.com"},
{ver:"Technology",des:"Krebs on security covering Computer security and Cybercrime.",api:"http://feeds.feedburner.com/KrebsOncategoryurity",ext:"https://krebsoncategoryurity.com"},
{ver:"Technology",des:"Los Angeles Times is a daily newspaper that is published in Los Angeles, California.",api:"https://www.latimes.com/business/technology/rss2.0.xml",ext:"https://latimes.com/business/technology"},
{ver:"Technology",des:"Lifehacker is the Ultimate Authority on optimizing every aspect of your life. Do everything better.",api:"https://lifehacker.com/rss",ext:"https://lifehacker.com"},
{ver:"Technology",des:"Leak-Lookup Latest Database Leaks and Records Counting.",api:"https://leak-lookup.com/rss",ext:"https://leak-lookup.com"},
{ver:"Technology",des:"Linux.com News For Open Source Professionals.",api:"https://www.linux.com/feed",ext:"https://linux.com"},
{ver:"Technology",des:"Medium's advice for Programmers covering Tutorials, Leadership, Management, and Productivity.",api:"https://medium.com/feed/better-programming",ext:"https://medium.com/better-programming"},
{ver:"Technology",des:"Mirror.co.uk Technologys' Best Stories, Opinion, Pictures and Video.",api:"https://www.mirror.co.uk/tech/?service=rss",ext:"https://mirror.co.uk/tech"},
{ver:"Technology",des:"MIT is a Top University, in Science and Engineering, Cognitive Science, Philosophy and Linguistics.",api:"http://news.mit.edu/rss/feed",ext:"http://news.mit.edu"},
{ver:"Technology",des:"NASA brings you the Latest Images, Videos and News from America's space agency.",api:"https://www.nasa.gov/rss/dyn/breaking_news.rss",ext:"https://nasa.gov"},
{ver:"Technology",des:"NBC News Tech for Latest News on Technology, Businesses and Internet media.",api:"http://feeds.nbcnews.com/nbcnews/public/tech",ext:"https://nbcnews.com/tech-media"},
{ver:"Technology",des:"New York Post technology, established Nov 16, 1801, describes itself as the nation's oldest daily newspaper.",api:"https://nypost.com/tech/feed",ext:"https://nypost.com/tech"},
{ver:"Technology",des:"New York Times is a Newspaper based in New York City with Worldwide Influence.",api:"https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",ext:"https://nytimes.com/categorytion/technology"},
{ver:"Technology",des:"Packet Storm is a Information Security website offering Current and Historical Computer Security Tools.",api:"https://rss.packetstormcategoryurity.com/news/tags/usa",ext:"https://packetstormcategoryurity.com"},
{ver:"Technology",des:"PC World is one of the United Kingdom's largest retail chains of Mass Market Computer Megastores.",api:"https://www.pcworld.com/index.rss",ext:"https://pcworld.com"},
{ver:"Technology",des:"Phoronix Linux Hardware Reviews & News.",api:"https://www.phoronix.com/rss.php",ext:"https://phoronix.com"},
{ver:"Technology",des:"Phys.org has Latest News on Science in Physics, Space Science, Earth Science, Health and Medicine.",api:"https://phys.org/rss-feed",ext:"https://phys.org"},
{ver:"Technology",des:"Politico Tech strives to be the dominant source for Politics and Policy.",api:"https://www.politico.com/rss/morningtech.xml",ext:"https://politico.com"},
{ver:"Technology",des:"Popular Mechanics is a magazine of Popular Science and Technology.",api:"https://www.popularmechanics.com/rss/all.xml",ext:"https://popularmechanics.com"},
{ver:"Technology",des:"ReadWrite was founded on April 20, 2003 as ReadWriteWeb.",api:"https://readwrite.com/feed",ext:"https://readwrite.com"},
{ver:"Technology",des:"Reclaim The Net - Restoring Individual Liberty Online. Free Speech. Privacy",api:"https://reclaimthenet.org/feed",ext:"https://reclaimthenet.org"},
{ver:"Technology",des:"ScienceDaily Top Technology News.",api:"https://www.sciencedaily.com/rss/top/technology.xml",ext:"https://sciencedaily.com/news/top/technology"},
{ver:"Technology",des:"Sky News Technology is a British news organisation, which operates a TV network.",api:"http://feeds.skynews.com/feeds/rss/technology.xml",ext:"https://sky.com/technology"},
{ver:"Technology",des:"Softpedia Linux is a software and Tech-News website based in Romania.",api:"https://linux.softpedia.com/backend.xml",ext:"https://linux.softpedia.com"},
{ver:"Technology",des:"TechCrunch Reports on the Business of Technology, Startups, Venture Capital funding, and Silicon Valley.",api:"http://feeds.feedburner.com/TechCrunch",ext:"https://techcrunch.com"},
{ver:"Technology",des:"TechMeme is an automated News curation service focused on the leading edge of Technology.",api:"https://www.techmeme.com/feed.xml",ext:"https://techmeme.com"},
{ver:"Technology",des:"TechRadar is an online Publication focused on Technology.",api:"https://www.techradar.com/rss",ext:"https://techradar.com"},
{ver:"Technology",des:"TechRepublic is an online Trade publication and social Community for IT Professionals.",api:"https://www.techrepublic.com/rssfeeds/articles",ext:"https://techrepublic.com"},
{ver:"Technology",des:"TechPowerUp is a leading Technology publication, on the forefront of PC Technologies.",api:"https://www.techpowerup.com/rss/news",ext:"https://techpowerup.com"},
{ver:"Technology",des:"TechSpot is a leading Computer and Technology publication established in 1998.",api:"https://www.techspot.com/backend.xml",ext:"https://techspot.com"},
{ver:"Technology",des:"Telegraph.co.uk Technology Intelligence news from the world of Technology.",api:"https://www.telegraph.co.uk/technology/rss.xml",ext:"https://www.telegraph.co.uk/technology"},
{ver:"Technology",des:"TheRegister.co.uk is a British Technology News and opinion website co-founded in 1994.",api:"https://www.theregister.co.uk/headlines.atom",ext:"https://theregister.co.uk"},
{ver:"Technology",des:"USA Today Technology is an internationally distributed American daily, middle-market Newspaper.",api:"http://rssfeeds.usatoday.com/usatoday-techtopstories&x=1",ext:"https://usatoday.com/tech/"},
{ver:"Technology",des:"Wall Street Journals Latest Tech News, Reviews, and Stories.",api:"https://feeds.a.dj.com/rss/RSSWSJD.xml",ext:"https://wsj.com/news/technology"},
{ver:"Technology",des:"Washington Post is a major American daily newspaper published in Washington, D.C.",api:"http://feeds.washingtonpost.com/rss/business/technology",ext:"https://washingtonpost.com/business/technology"},
{ver:"Technology",des:"Washington Times is an American daily newspaper published in Washington, D.C.",api:"https://www.washingtontimes.com/rss/headlines/culture/technology",ext:"https://washingtontimes.com/culture/technology"},
{ver:"Technology",des:"Wccftech has the Latest updates in the world of Tech, Mobile, PC Hardware, Gaming & Finance.",api:"https://wccftech.com/feed",ext:"https://wccftech.com"},
{ver:"Technology",des:"WIRED is where tomorrow is realized. It is the essential source of information.",api:"https://www.wired.com/feed/rss",ext:"https://wired.com"},
{ver:"Technology",des:"Yahoo is a web services provider headquartered in California, and owned by Verizon Media.",api:"https://www.yahoo.com/tech/rss",ext:"https://finance.yahoo.com/tech"},
{ver:"Technology",des:"ZDNet is a business technology news website published by CBS Interactive.",api:"https://www.zdnet.com/news/rss.xml",ext:"https://zdnet.com"},
{ver:"World",des:"ABC is an American broadcast television network that is property of Walt Disney.",api:"https://abcnews.go.com/abcnews/internationalheadlines",ext:"https://abc.com"},
{ver:"World",des:"BBC is the world’s leading public service broadcaster.",api:"http://feeds.bbci.co.uk/news/rss.xml",ext:"https://bbc.com"},
{ver:"World",des:"Bloomberg delivers business and markets news, data, analysis, and video.",api:"https://www.bloomberg.com/view/rss",ext:"https://bloomberg.com"},
{ver:"World",des:"Boston.com is a regional website that offers news and information about Boston, Massachusetts.",api:"https://www.boston.com/tag/world-news/feed",ext:"https://www.boston.com/tag/world-news"},
{ver:"World",des:"Boston Herald is the leading source of breaking news, local news, sports, politics, and entertainment.",api:"https://www.bostonherald.com/feed",ext:"https://www.bostonherald.com"},
{ver:"World",des:"CBS is a media company that creates and distributes industry-leading content.",api:"https://www.cbsnews.com/latest/rss/world",ext:"https://cbsnews.com"},
{ver:"World",des:"CNBC latest headlines from around the world.",api:"https://www.cnbc.com/id/100727362/device/rss/rss.html",ext:"https://cnbc.com/world"},
{ver:"World",des:"CNN is among the world's leaders in online news and information delivery.",api:"http://rss.cnn.com/rss/cnn_topstories.rss",ext:"https://cnn.com"},
{ver:"World",des:"Daily Mail is a British daily middle-market newspaper published in London.",api:"https://www.dailymail.co.uk/articles.rss",ext:"https://dailymail.co.uk"},
{ver:"World",des:"Digital Trends’ team of experienced staffers provide the latest news.",api:"https://www.digitaltrends.com/news/feed",ext:"https://digitaltrends.com/news"},
{ver:"World",des:"Drudge Report consists mainly of news stories from other outlets.",api:"http://feeds.feedburner.com/DrudgeReportFeed",ext:"https://drudgereport.com"},
{ver:"World",des:"Fox News breaking news, Latest news, and Current news.",api:"http://feeds.foxnews.com/foxnews/latest",ext:"https://foxnews.com"},
{ver:"World",des:"Google is a multinational technology company that specializes in Internet-related services and products.",api:"https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",ext:"https://news.google.com"},
{ver:"World",des:"Mirror.co.uk World headlines, pictures, analysis, opinion and video.",api:"https://www.mirror.co.uk/news/us-news/?service=rss",ext:"https://mirror.co.uk/news/us-news"},
{ver:"World",des:"Mercury News is passionate about serving readers in Silicon Valley and its global technology community.",api:"https://www.mercurynews.com/feed",ext:"https://mercurynews.com"},
{ver:"World",des:"MSN is a web portal of Internet services and apps for Windows and mobile devices.",api:"http://rss.msn.com",ext:"https://msn.com"},
{ver:"World",des:"NBC News is the news division of the American broadcast television network NBC.",api:"http://feeds.nbcnews.com/nbcnews/public/news",ext:"https://nbcnews.com"},
{ver:"World",des:"News subreddit articles relating to the United States and the rest of the World.",api:"https://reddit.com/r/news/.rss",ext:"https://reddit.com/r/news"},
{ver:"World",des:"NPR is an independent, nonprofit media organization that was founded to create a more informed public.",api:"https://www.npr.org/rss/rss.php?id=1019",ext:"https://npr.org"},
{ver:"World",des:"Public Broadcasting Service is an American public broadcaster and television program distributor.",api:"https://www.pbs.org/newshour/feeds/rss/headlines",ext:"https://pbs.org"},
{ver:"World",des:"World News subreddit with latest headlines from around the world.",api:"https://reddit.com/r/worldnews/.rss",ext:"https://reddit.com/r/worldnews"},
{ver:"World",des:"RT delivers latest news on current events from around the world.",api:"https://www.rt.com/rss",ext:"https://rt.com"},
{ver:"World",des:"San Francisco Gate is the Hearst-owned website sister-site of the San Francisco Chronicle.",api:"https://www.sfgate.com/rss/feed/Business-and-Technology-News-448.php",ext:"https://sfgate.com/technology"},
{ver:"World",des:"Sputnik is a major new media brand with modern multimedia centers in dozens of countries.",api:"https://sputniknews.com/export/rss2/archive/index.xml",ext:"https://sputniknews.com"},
{ver:"World",des:"Newsweek provides the latest news about international issues, technology, business, culture and politics.",api:"https://www.newsweek.com/rss",ext:"https://newsweek.com"},
{ver:"World",des:"New York Daily News news coverage, sports, entertainment news, celebrity gossip, autos, videos and photos.",api:"https://www.nydailynews.com/cmlink/NYDN.News.World.rss",ext:"https://www.nydailynews.com/news/world"},
{ver:"World",des:"New York Post is a daily newspaper in New York City.",api:"https://nypost.com/feed",ext:"https://nypost.com"},
{ver:"World",des:"Telegraph.co.uk for the latest news from the UK and around the world.",api:"https://www.telegraph.co.uk/rss.xml",ext:"https://www.telegraph.co.uk"},
{ver:"World",des:"The Age National News from Australia, World News, Business News and Breaking News stories.",api:"https://www.theage.com.au/rss/feed.xml",ext:"https://www.theage.com.au"},
{ver:"World",des:"Time Magazine is one of the most authoritative and informative guides to what is happening in the world.",api:"http://feeds.feedburner.com/time/topstories?format=xml",ext:"https://time.com"},
{ver:"World",des:"United Press International is a leading provider of news, photos and information.",api:"https://rss.upi.com/news/news.rss",ext:"https://upi.com"},
{ver:"World",des:"USA Today delivers local and national news, sports, entertainment, finance, technology, and more.",api:"http://rssfeeds.usatoday.com/usatoday-newstopstories&x=1",ext:"https://www.usatoday.com"},
{ver:"World",des:"Vice Original reporting and documentaries on everything that matters in the world.",api:"https://www.vice.com/en_us/rss",ext:"https://vice.com"},
{ver:"World",des:"Washington Times World News, Middle East News, Afghanistan War.",api:"https://www.washingtontimes.com/rss/headlines/news/world",ext:"https://washingtontimes.com/news/world"}
]
